import type { DomainContent } from '../knowledge-core/types';

// Wine v0 — Block 1 (systematic tasting + pairing logic), the country-labelling insight,
// and classic appellation facts. All items are stable, factual, and public (appellation
// regulations / grape composition). source + verified per the accuracy gate; Simon should
// still spot-check specifics per spec 02 §3 before relying on them.
export const WINE: DomainContent = {
  id: 'wine',
  title: 'Wine',
  blurb: 'Tasting · regions · grapes',
  accent: '#7b2f3f',
  newPerDay: 6,
  blocks: [
    {
      id: 'tasting',
      title: 'Systematic tasting',
      primer: 'Before any bottle can teach you anything, you need a fixed structure to taste against. Without one, every wine is an isolated impression you forget by the next glass.\n\nWith one, each bottle becomes a data point you can compare across regions, grapes and years. Assess the same six things, in the same order, every time.',
      lessons: [
        {
          id: 'six-axes',
          title: 'The six axes',
          diagram: '<svg viewBox="0 0 340 208" xmlns="http://www.w3.org/2000/svg" font-family="-apple-system, sans-serif">' +
            '<circle cx="18" cy="24" r="5" fill="var(--accent)"/><text x="34" y="28" font-size="14" font-weight="600" fill="var(--plat-text)">Acid</text><text x="150" y="28" font-size="12" fill="var(--plat-muted)">freshness · backbone</text>' +
            '<circle cx="18" cy="56" r="5" fill="var(--accent)"/><text x="34" y="60" font-size="14" font-weight="600" fill="var(--plat-text)">Tannin</text><text x="150" y="60" font-size="12" fill="var(--plat-muted)">grip · structure (reds)</text>' +
            '<circle cx="18" cy="88" r="5" fill="var(--accent)"/><text x="34" y="92" font-size="14" font-weight="600" fill="var(--plat-text)">Alcohol</text><text x="150" y="92" font-size="12" fill="var(--plat-muted)">warmth</text>' +
            '<circle cx="18" cy="120" r="5" fill="var(--accent)"/><text x="34" y="124" font-size="14" font-weight="600" fill="var(--plat-text)">Body</text><text x="150" y="124" font-size="12" fill="var(--plat-muted)">weight · texture</text>' +
            '<circle cx="18" cy="152" r="5" fill="var(--accent)"/><text x="34" y="156" font-size="14" font-weight="600" fill="var(--plat-text)">Fruit</text><text x="150" y="156" font-size="12" fill="var(--plat-muted)">ripeness · profile</text>' +
            '<circle cx="18" cy="184" r="5" fill="var(--accent)"/><text x="34" y="188" font-size="14" font-weight="600" fill="var(--plat-text)">Finish</text><text x="150" y="188" font-size="12" fill="var(--plat-muted)">length</text>' +
            '</svg>',
          body: 'Acid is the wine’s freshness and backbone — it makes your mouth water and keeps a wine lively. High acid feels tart and crisp; low acid feels soft, even flabby.\n\nTannin is the drying, grippy sensation on your gums, mostly in reds, from grape skins and oak. It gives structure and ageing potential.\n\nAlcohol is felt as warmth; body is the wine’s overall weight and texture — light like skim milk, or full like cream.\n\nFruit describes the ripeness and flavour family (citrus, stone fruit, red or black berry). Finish is how long the flavour lasts after you swallow — a long finish is a mark of quality.',
        },
        {
          id: 'pairing-logic',
          title: 'Pairing is logic, not lists',
          body: 'You don’t memorise pairings — you reason them from four rules.\n\nMatch acidity to fat: a high-acid wine cuts through rich, fatty food and refreshes the palate.\n\nMatch tannin to protein: tannin binds with protein and fat, so a tannic red feels smoother beside a steak than on its own.\n\nKeep the wine’s sweetness above the dish’s: a wine less sweet than the dessert tastes thin and sour.\n\nMatch weight to weight: a delicate dish is flattened by a heavy wine, and vice versa.',
        },
      ],
    },
    {
      id: 'labelling',
      title: 'What the label tells you',
      primer: 'Here is the single most useful thing to learn about wine: every country answers “what does the label tell you?” differently.\n\nLearn each country’s organising principle and you can read a label you’ve never seen before — worth more than memorising any individual appellation.',
      lessons: [
        { id: 'lab-france', title: 'France — by place', body: 'France labels by PLACE. The grape is usually absent — a red Burgundy says “Gevrey-Chambertin”, not “Pinot Noir”, because the appellation implies the grape and style.\n\nMost French regions blend: Bordeaux (Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, Malbec), the southern Rhône (Grenache-Syrah-Mourvèdre), Champagne (Chardonnay, Pinot Noir, Meunier).\n\nThe exception is Burgundy: monovarietal (Pinot Noir or Chardonnay) yet still labelled by place. The rule holds; the blending habit doesn’t.' },
        { id: 'lab-italy', title: 'Italy — place + native grape', body: 'Italy labels by PLACE plus its NATIVE GRAPE, under the DOC/DOCG system, with enormous varietal diversity.\n\nBrunello di Montalcino is 100% Sangiovese; Barolo and Barbaresco are 100% Nebbiolo; Chianti Classico is at least 80% Sangiovese. The place tells you the rules; the grape tells you the character.' },
        { id: 'lab-spain', title: 'Spain — grape + time in oak', body: 'Spain often labels by GRAPE plus TIME IN OAK AND BOTTLE. The ladder Joven → Crianza → Reserva → Gran Reserva is an AGEING classification — not a region, and not a quality tier, a point widely misread.\n\nA Gran Reserva has simply spent the most time maturing before release.' },
        { id: 'lab-germany', title: 'Germany — grape + ripeness', body: 'Germany labels by GRAPE plus RIPENESS AT HARVEST. The Prädikat ladder — Kabinett → Spätlese → Auslese → Beerenauslese → Trockenbeerenauslese — measures must weight (sugar/ripeness when picked), not the sweetness of the finished wine.\n\nA Kabinett can be made bone dry.' },
        { id: 'lab-newworld', title: 'New World — grape first', body: 'The New World (California, Australia, Chile and the rest) labels by GRAPE first, region second — the inverse of France. “Barossa Shiraz” names the grape, then the place.\n\nIt’s the most immediately readable system, and the reason France can feel opaque by comparison.' },
      ],
    },
    {
      id: 'regions',
      title: 'A few anchor regions',
      primer: 'The atomic unit of wine study is a single appellation — small enough to learn in one sitting, rich enough to be worth it.\n\nAn “introduction to Italian wine” is one overview; the real learning is region by region. Here are a few anchors; the review cards drill the specifics.',
      lessons: [
        { id: 'reg-italy', title: 'Italy: Piedmont & Tuscany', body: 'Piedmont’s Barolo and Barbaresco are 100% Nebbiolo — pale in colour, high in acid and tannin, powerful despite looking delicate.\n\nIn Tuscany, Sangiovese rules: Brunello di Montalcino (100% Sangiovese from the warmer Montalcino climate, five years’ minimum ageing) and Chianti Classico (at least 80% Sangiovese).' },
        { id: 'reg-france', title: 'France: the classics', body: 'Bordeaux blends its five reds to hedge site and vintage. Burgundy splits into tiny place-named plots of Pinot Noir and Chardonnay.\n\nThe southern Rhône’s GSM (Grenache-Syrah-Mourvèdre) powers Châteauneuf-du-Pape. Champagne blends Chardonnay, Pinot Noir and Meunier — and is a place, not merely a style.' },
      ],
    },
  ],
  cards: [
    // --- Block 1: systematic tasting + pairing logic ---
    { id: 'w-taste-axes', type: 'why', prompt: 'Systematic tasting fixes the things you assess in every glass. What are they?',
      explanation: 'Acid, tannin, alcohol, body, fruit, finish — a fixed structure so every bottle becomes a comparable data point rather than an anecdote.',
      source: 'Spec 03 §Wine, block 1', verified: true, tag: 'tasting' },
    { id: 'w-taste-first', type: 'why', prompt: 'Why taste to a fixed structure from the very first bottle?',
      explanation: 'Without a structure, each subsequent bottle is an isolated impression. With one, you build a mental library you can compare across regions and vintages.',
      source: 'Spec 03 §Wine', verified: true, tag: 'tasting' },
    { id: 'w-pair-acid', type: 'cloze', prompt: 'Pairing logic: match acidity to ___ (rich, fatty dishes).',
      answer: 'fat', accept: ['fat', 'fatty', 'richness'], explanation: 'Acid cuts through fat and refreshes the palate — think a crisp white with fried food.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing' },
    { id: 'w-pair-tannin', type: 'cloze', prompt: 'Pairing logic: match tannin to ___ (it binds and softens against it).',
      answer: 'protein', accept: ['protein', 'proteins'], explanation: 'Tannin binds with protein and fat, so a tannic red feels smoother with a steak than on its own.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing' },
    { id: 'w-pair-sweet', type: 'cloze', prompt: 'Pairing a dessert: the wine’s sweetness should sit ___ the dish’s sweetness.',
      answer: 'above', accept: ['above', 'higher'], explanation: 'A wine less sweet than the dessert tastes thin and sour beside it — sweet wine must out-sweet the plate.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing' },
    { id: 'w-pair-weight', type: 'cloze', prompt: 'Pairing logic: match the ___ of the wine to the weight of the dish.',
      answer: 'weight', accept: ['weight', 'body'], explanation: 'A light dish is flattened by a heavy wine and vice versa — weight to weight, body to body.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing' },

    // --- The structural insight the module is built on ---
    { id: 'w-label-fr-nw', type: 'why', prompt: 'Each wine country answers “what does the label tell you?” differently. What are France’s and the New World’s answers?',
      explanation: 'France labels by PLACE (appellation) — the grape is usually absent. The New World labels by GRAPE first, region second. Learning that difference is worth more than any single appellation.',
      source: 'Spec 03 §Wine, organising principle', verified: true, tag: 'labelling' },
    { id: 'w-burgundy-exception', type: 'why', prompt: 'Burgundy is France’s exception to place-labelling. How?',
      explanation: 'It is monovarietal — Pinot Noir for reds, Chardonnay for whites — yet still labelled by PLACE, not grape. The rule (label by place) holds; the blending norm does not.',
      source: 'Spec 03 §Wine, France', verified: true, tag: 'France' },

    // --- Classic appellation / grape facts ---
    { id: 'w-brunello', type: 'instance', prompt: 'Brunello di Montalcino is made from 100% which grape?',
      answer: 'Sangiovese', accept: ['sangiovese'], explanation: 'Brunello is 100% Sangiovese from the warmer, drier Montalcino mesoclimate, with long ageing (min. five years).',
      source: 'DOCG regulations', verified: true, tag: 'Italy' },
    { id: 'w-barolo', type: 'instance', prompt: 'Barolo and Barbaresco are made from 100% which grape?',
      answer: 'Nebbiolo', accept: ['nebbiolo'], explanation: 'Both Piedmont DOCGs are 100% Nebbiolo — high acid, high tannin, pale colour that belies its power.',
      source: 'DOCG regulations', verified: true, tag: 'Italy' },
    { id: 'w-chianti', type: 'cloze', prompt: 'Chianti Classico must be at least ___% Sangiovese.',
      answer: '80', accept: ['80', '80%'], explanation: 'Chianti Classico requires a minimum 80% Sangiovese, with the rest from permitted local or international grapes.',
      source: 'DOCG regulations', verified: true, tag: 'Italy' },
    { id: 'w-gsm', type: 'instance', prompt: 'The southern Rhône “GSM” blend is Grenache, Syrah, and ___.',
      answer: 'Mourvèdre', accept: ['mourvedre', 'mourvèdre'], explanation: 'Grenache (fruit/warmth), Syrah (structure/spice), Mourvèdre (savoury grip) — the backbone of Châteauneuf-du-Pape and much of the south.',
      source: 'Appellation practice', verified: true, tag: 'France' },
    { id: 'w-bordeaux', type: 'why', prompt: 'Name the principal red grapes permitted in a classic Bordeaux blend.',
      explanation: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, and Malbec. Bordeaux blends rather than relying on one grape — the mix hedges vintage and site.',
      source: 'Appellation practice', verified: true, tag: 'France' },
    { id: 'w-rioja-ladder', type: 'cloze', prompt: 'Spain’s ageing ladder: Joven → Crianza → Reserva → ___.',
      answer: 'Gran Reserva', accept: ['gran reserva', 'granreserva'], explanation: 'Each step requires more time in oak and bottle before release.',
      source: 'Spanish DO ageing rules', verified: true, tag: 'Spain' },
    { id: 'w-rioja-meaning', type: 'why', prompt: 'In Spain, what do Crianza / Reserva / Gran Reserva classify — and what is it commonly misread as?',
      explanation: 'They classify TIME IN OAK AND BOTTLE (ageing), not the region or inherent quality. It is widely misread as a quality or origin tier — it is an ageing scale.',
      source: 'Spec 03 §Wine, Spain', verified: true, tag: 'Spain' },
    { id: 'w-pradikat', type: 'cloze', prompt: 'Germany’s Prädikat ripeness ladder: Kabinett → Spätlese → Auslese → BA → ___.',
      answer: 'TBA', accept: ['tba', 'trockenbeerenauslese'], explanation: 'Trockenbeerenauslese (TBA) — from individually selected botrytised, shrivelled berries.',
      source: 'German wine law', verified: true, tag: 'Germany' },
    { id: 'w-pradikat-meaning', type: 'why', prompt: 'German Prädikat levels (Kabinett…TBA) measure what, exactly?',
      explanation: 'Must weight — the sugar/ripeness of the grapes AT HARVEST — not the sweetness of the finished wine. A Kabinett can be made bone dry.',
      source: 'Spec 03 §Wine, Germany', verified: true, tag: 'Germany' },
    { id: 'w-champagne', type: 'instance', prompt: 'Champagne’s three principal grapes are Chardonnay, Pinot Noir, and ___.',
      answer: 'Meunier', accept: ['meunier', 'pinot meunier'], explanation: 'Meunier adds fruit and approachability; Chardonnay finesse; Pinot Noir structure.',
      source: 'Appellation practice', verified: true, tag: 'Champagne' },
  ],

  // Equirectangular pins (x = lon+180, y = 90−lat) over the stylised world outline.
  mapPins: [
    { entryId: 'r-bordeaux', label: 'Bordeaux', x: 179, y: 45 },
    { entryId: 'r-burgundy', label: 'Burgundy', x: 185, y: 43 },
    { entryId: 'r-champagne', label: 'Champagne', x: 184, y: 41 },
    { entryId: 'r-rhone', label: 'Rhône', x: 186, y: 46 },
    { entryId: 'r-piedmont', label: 'Piedmont', x: 188, y: 45 },
    { entryId: 'r-tuscany', label: 'Tuscany', x: 191, y: 47 },
    { entryId: 'r-rioja', label: 'Rioja', x: 177, y: 48 },
    { entryId: 'r-douro', label: 'Douro', x: 172, y: 49 },
    { entryId: 'r-mosel', label: 'Mosel', x: 187, y: 40 },
    { entryId: 'r-napa', label: 'Napa', x: 58, y: 52 },
    { entryId: 'r-willamette', label: 'Willamette', x: 57, y: 45 },
    { entryId: 'r-mendoza', label: 'Mendoza', x: 111, y: 123 },
    { entryId: 'r-maipo', label: 'Maipo', x: 108, y: 124 },
    { entryId: 'r-barossa', label: 'Barossa', x: 319, y: 125 },
    { entryId: 'r-marlborough', label: 'Marlborough', x: 351, y: 132 },
    { entryId: 'r-stellenbosch', label: 'Stellenbosch', x: 199, y: 124 },
  ],

  explore: [
    {
      id: 'regions',
      title: 'Anchor regions',
      blurb: 'Tap a pin on the map, or a card below. Each is a one-pager you can read in a minute.',
      kind: 'gallery',
      entries: [
        { id: 'r-bordeaux', title: 'Bordeaux', subtitle: 'France · Cabernet/Merlot blends',
          facts: [ { label: 'Country', value: 'France' }, { label: 'Signature', value: 'Cab. Sauvignon, Merlot' }, { label: 'Style', value: 'Structured, age-worthy reds' }, { label: 'Split', value: 'Left Bank (Cab) vs Right Bank (Merlot)' } ],
          body: 'Bordeaux is the reference point for blended reds. The Left Bank (Médoc, Graves) is Cabernet Sauvignon–led — firm tannin, cassis, cedar, built to age. The Right Bank (Saint-Émilion, Pomerol) is Merlot-led — rounder, plummier, approachable younger.\n\nBlending across five permitted grapes (Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, Malbec) is the whole point: it hedges an uncertain maritime vintage and site. It also makes sweet whites in Sauternes from botrytised Sémillon and Sauvignon Blanc.',
          source: 'Appellation regulations' },
        { id: 'r-burgundy', title: 'Burgundy', subtitle: 'France · Pinot Noir & Chardonnay',
          facts: [ { label: 'Country', value: 'France' }, { label: 'Reds', value: 'Pinot Noir' }, { label: 'Whites', value: 'Chardonnay' }, { label: 'Logic', value: 'Single grape, labelled by place' } ],
          body: 'Burgundy is the great exception: monovarietal wines still labelled by PLACE, not grape. A hierarchy of ever-smaller plots — regional → village → Premier Cru → Grand Cru — expresses the belief that the vineyard, not the winemaker, is the author.\n\nReds are Pinot Noir (perfumed, red-fruited, translucent); whites are Chardonnay (from steely Chablis in the north to rich Meursault in the Côte de Beaune).',
          source: 'Appellation regulations' },
        { id: 'r-champagne', title: 'Champagne', subtitle: 'France · traditional-method sparkling',
          facts: [ { label: 'Country', value: 'France' }, { label: 'Grapes', value: 'Chardonnay, Pinot Noir, Meunier' }, { label: 'Method', value: 'Second fermentation in bottle' }, { label: 'Note', value: 'A place, not just a style' } ],
          body: 'Champagne is a cool northern region whose bubbles come from a second fermentation IN the bottle (the traditional method), which traps CO₂ and builds the fine, persistent mousse and bready autolytic character.\n\n“Blanc de Blancs” is 100% Chardonnay; “Blanc de Noirs” is from the black grapes (Pinot Noir, Meunier) pressed pale. Most Champagne is non-vintage — a house blend across years for consistency.',
          source: 'Appellation practice' },
        { id: 'r-rhone', title: 'Rhône Valley', subtitle: 'France · Syrah (north) · GSM (south)',
          facts: [ { label: 'Country', value: 'France' }, { label: 'North', value: '100% Syrah (Côte-Rôtie, Hermitage)' }, { label: 'South', value: 'GSM blends (Châteauneuf-du-Pape)' }, { label: 'Style', value: 'Peppery to warm & spicy' } ],
          body: 'Two Rhônes. The steep northern Rhône is Syrah — black pepper, olive, violets — sometimes co-fermented with a splash of white Viognier in Côte-Rôtie.\n\nThe warmer, flatter south is blend country: Grenache-Syrah-Mourvèdre (GSM) plus more, over the galets (large round stones) of Châteauneuf-du-Pape, which store heat and reflect it into the vines.',
          source: 'Appellation practice' },
        { id: 'r-piedmont', title: 'Piedmont', subtitle: 'Italy · Nebbiolo',
          facts: [ { label: 'Country', value: 'Italy' }, { label: 'Grape', value: '100% Nebbiolo (Barolo, Barbaresco)' }, { label: 'Profile', value: 'Pale colour, high acid & tannin' }, { label: 'Also', value: 'Barbera, Dolcetto, Moscato' } ],
          body: 'Piedmont’s Barolo and Barbaresco are 100% Nebbiolo — deceptively pale and light-looking, yet fiercely tannic, high in acid, and long-lived, with tar-and-roses aromatics.\n\nEveryday drinking comes from juicy Barbera and soft Dolcetto; sweet, gently fizzy Moscato d’Asti is the region’s famous low-alcohol white.',
          source: 'DOCG regulations' },
        { id: 'r-tuscany', title: 'Tuscany', subtitle: 'Italy · Sangiovese',
          facts: [ { label: 'Country', value: 'Italy' }, { label: 'Grape', value: 'Sangiovese' }, { label: 'Wines', value: 'Chianti Classico, Brunello di Montalcino' }, { label: 'Also', value: '“Super Tuscans” (Bordeaux blends)' } ],
          body: 'Sangiovese rules Tuscany: sour-cherry fruit, savoury herbs, brisk acidity. Chianti Classico is ≥80% Sangiovese; Brunello di Montalcino is 100% Sangiovese from a warmer site with long ageing (min. five years).\n\nThe “Super Tuscans” broke the old rules in the 1970s by blending in Cabernet and Merlot — initially sold as humble table wine, now among Italy’s most prized.',
          source: 'DOCG regulations' },
        { id: 'r-rioja', title: 'Rioja', subtitle: 'Spain · Tempranillo',
          facts: [ { label: 'Country', value: 'Spain' }, { label: 'Grape', value: 'Tempranillo (+ Garnacha)' }, { label: 'Ladder', value: 'Joven → Crianza → Reserva → Gran Reserva' }, { label: 'Signature', value: 'American-oak vanilla & dill' } ],
          body: 'Rioja is Tempranillo country, traditionally married to American oak that lends a signature vanilla, coconut and dill note. The label’s Crianza/Reserva/Gran Reserva ladder measures TIME IN OAK AND BOTTLE — not quality or origin.\n\nA Gran Reserva is released only after years of ageing, arriving mellow and savoury; a Joven is unoaked and fruity.',
          source: 'Spanish DO rules' },
        { id: 'r-douro', title: 'Douro', subtitle: 'Portugal · Port & dry reds',
          facts: [ { label: 'Country', value: 'Portugal' }, { label: 'Grapes', value: 'Touriga Nacional & field blends' }, { label: 'Famous for', value: 'Port (fortified)' }, { label: 'Terrain', value: 'Steep schist terraces' } ],
          body: 'The Douro’s steep schist terraces gave the world Port — a red fortified by adding grape spirit mid-fermentation, which stops the yeast and leaves the wine sweet and strong.\n\nThe same indigenous grapes (Touriga Nacional foremost) now make serious dry reds, powerful and floral, that put the region on the fine-wine map beyond fortifieds.',
          source: 'Regional practice' },
        { id: 'r-mosel', title: 'Mosel', subtitle: 'Germany · Riesling',
          facts: [ { label: 'Country', value: 'Germany' }, { label: 'Grape', value: 'Riesling' }, { label: 'Style', value: 'Low alcohol, high acid, off-dry to sweet' }, { label: 'Ladder', value: 'Prädikat = ripeness at harvest' } ],
          body: 'The Mosel’s slate slopes make some of the world’s most delicate Rieslings — often just 8–9% alcohol, with racing acidity balanced by a touch of sweetness, and an unmistakable “petrol” note with age.\n\nThe Prädikat ladder (Kabinett → Spätlese → Auslese → BA → TBA) grades the grapes’ ripeness AT HARVEST, not the finished sweetness: a Kabinett can be bone dry (“trocken”).',
          source: 'German wine law' },
        { id: 'r-napa', title: 'Napa Valley', subtitle: 'USA · Cabernet Sauvignon',
          facts: [ { label: 'Country', value: 'USA (California)' }, { label: 'Grape', value: 'Cabernet Sauvignon' }, { label: 'Style', value: 'Ripe, full-bodied, generous oak' }, { label: 'Labelled by', value: 'Grape first (New World)' } ],
          body: 'Napa is the New World’s Cabernet benchmark: warm days and cool nights give ripe, plush, high-alcohol reds with cassis and vanilla-toast oak. Hillside sites (Howell Mountain) add structure; valley floor gives opulence.\n\nLike the rest of the New World, it labels by grape first — the inverse of France.',
          source: 'Regional practice' },
        { id: 'r-willamette', title: 'Willamette Valley', subtitle: 'USA · Pinot Noir',
          facts: [ { label: 'Country', value: 'USA (Oregon)' }, { label: 'Grape', value: 'Pinot Noir' }, { label: 'Climate', value: 'Cool, marginal' }, { label: 'Style', value: 'Burgundian — bright, red-fruited' } ],
          body: 'Cool, rainy Oregon turned out to be ideal for Pinot Noir, producing a more restrained, Burgundian style than California — bright red fruit, fresh acidity, earthy undertones.\n\nIt is the American reference for those who find Napa Cabernet too heavy.',
          source: 'Regional practice' },
        { id: 'r-mendoza', title: 'Mendoza', subtitle: 'Argentina · Malbec',
          facts: [ { label: 'Country', value: 'Argentina' }, { label: 'Grape', value: 'Malbec' }, { label: 'Altitude', value: 'High-altitude Andes foothills' }, { label: 'Style', value: 'Plush, dark-fruited, velvety' } ],
          body: 'Malbec, a minor Bordeaux blending grape, found its home in high-altitude Mendoza, where intense sunlight and cool nights give deeply coloured, velvety reds full of black plum and violet.\n\nAltitude (often 900–1,500 m) preserves acidity and freshness that the warmth would otherwise burn off.',
          source: 'Regional practice' },
        { id: 'r-barossa', title: 'Barossa Valley', subtitle: 'Australia · Shiraz',
          facts: [ { label: 'Country', value: 'Australia' }, { label: 'Grape', value: 'Shiraz (Syrah)' }, { label: 'Style', value: 'Rich, full, sweet-fruited, spicy' }, { label: 'Vines', value: 'Some of the world’s oldest' } ],
          body: 'The warm Barossa makes the archetypal Australian Shiraz — full-bodied, high in alcohol, with blackberry, licorice and a warm spice, often matured in American oak.\n\nIt holds some of the oldest continuously producing vines on earth (pre-phylloxera plantings from the 1800s), prized for their concentration.',
          source: 'Regional practice' },
        { id: 'r-marlborough', title: 'Marlborough', subtitle: 'New Zealand · Sauvignon Blanc',
          facts: [ { label: 'Country', value: 'New Zealand' }, { label: 'Grape', value: 'Sauvignon Blanc' }, { label: 'Style', value: 'Pungent, zesty, unmistakable' }, { label: 'Notes', value: 'Passionfruit, gooseberry, cut grass' } ],
          body: 'Marlborough put New Zealand on the map with a Sauvignon Blanc so distinctive it created its own style: explosively aromatic, zesty and green, with passionfruit and gooseberry over a herbal snap.\n\nThe cool, sunny climate and long ripening season concentrate those pungent aromatics.',
          source: 'Regional practice' },
        { id: 'r-stellenbosch', title: 'Stellenbosch', subtitle: 'South Africa · Cabernet & Chenin',
          facts: [ { label: 'Country', value: 'South Africa' }, { label: 'Reds', value: 'Cabernet Sauvignon, Syrah' }, { label: 'Whites', value: 'Chenin Blanc' }, { label: 'Unique', value: 'Pinotage (Pinot × Cinsault)' } ],
          body: 'Stellenbosch is South Africa’s red heartland — structured Cabernet and Syrah from mountain slopes — while Chenin Blanc (locally “Steen”) is the country’s versatile white workhorse.\n\nPinotage, a local crossing of Pinot Noir and Cinsault, is the signature grape: dark, smoky, and divisive.',
          source: 'Regional practice' },
      ],
    },
    {
      id: 'grapes',
      title: 'Grapes to know',
      blurb: 'The dozen varieties that unlock most wine lists.',
      kind: 'list',
      entries: [
        { id: 'g-cabernet', title: 'Cabernet Sauvignon', subtitle: 'Red · full-bodied, high tannin',
          facts: [ { label: 'Home', value: 'Bordeaux (Left Bank)' }, { label: 'Also', value: 'Napa, Coonawarra, Tuscany' }, { label: 'Flavours', value: 'Cassis, cedar, green pepper' } ],
          body: 'The world’s most planted premium red — firm tannin, blackcurrant, and a savoury cedar/tobacco note with age. Thick skins give colour and structure; it blends famously with Merlot to soften.',
          source: 'Ampelography / regional practice' },
        { id: 'g-merlot', title: 'Merlot', subtitle: 'Red · plush, medium tannin',
          facts: [ { label: 'Home', value: 'Bordeaux (Right Bank)' }, { label: 'Flavours', value: 'Plum, black cherry, chocolate' } ],
          body: 'Softer and rounder than Cabernet, with plummy fruit and lower tannin — approachable young. It dominates the Right Bank (Pomerol, Saint-Émilion) and rescues countless blends from harshness.',
          source: 'Ampelography / regional practice' },
        { id: 'g-pinot', title: 'Pinot Noir', subtitle: 'Red · light, delicate, high acid',
          facts: [ { label: 'Home', value: 'Burgundy' }, { label: 'Also', value: 'Oregon, NZ, Germany (Spätburgunder)' }, { label: 'Flavours', value: 'Red cherry, raspberry, forest floor' } ],
          body: 'Thin-skinned and fussy to grow, Pinot Noir rewards effort with perfumed, translucent, silky reds. It is the great terroir transmitter — the reason Burgundy obsesses over single plots.',
          source: 'Ampelography / regional practice' },
        { id: 'g-chardonnay', title: 'Chardonnay', subtitle: 'White · the shape-shifter',
          facts: [ { label: 'Home', value: 'Burgundy' }, { label: 'Range', value: 'Steely (Chablis) → rich, oaked (Napa)' }, { label: 'In', value: 'Champagne (Blanc de Blancs)' } ],
          body: 'A near-neutral grape that reflects place and winemaking: unoaked and mineral in cool Chablis, buttery and tropical when warm-grown and oak-aged. Its malleability made it the world’s benchmark white.',
          source: 'Ampelography / regional practice' },
        { id: 'g-sangiovese', title: 'Sangiovese', subtitle: 'Red · savoury, high acid',
          facts: [ { label: 'Home', value: 'Tuscany' }, { label: 'Wines', value: 'Chianti, Brunello' }, { label: 'Flavours', value: 'Sour cherry, tomato leaf, herbs' } ],
          body: 'Italy’s most planted grape — bright acidity and grippy tannin that make it a natural at the table. Savoury and herbal rather than sweetly fruity, it is the backbone of Tuscan reds.',
          source: 'Ampelography / regional practice' },
        { id: 'g-nebbiolo', title: 'Nebbiolo', subtitle: 'Red · pale but powerful',
          facts: [ { label: 'Home', value: 'Piedmont' }, { label: 'Wines', value: 'Barolo, Barbaresco' }, { label: 'Flavours', value: 'Tar, roses, dried cherry' } ],
          body: 'A study in contradiction: pale garnet colour hiding ferocious tannin and acidity, with haunting tar-and-roses aromatics. Needs age (or decanting) to soften.',
          source: 'Ampelography / regional practice' },
        { id: 'g-syrah', title: 'Syrah / Shiraz', subtitle: 'Red · dark, peppery to jammy',
          facts: [ { label: 'Home', value: 'Northern Rhône' }, { label: 'As Shiraz', value: 'Australia (riper, sweeter)' }, { label: 'Flavours', value: 'Blackberry, black pepper, smoke' } ],
          body: 'Cool-climate Syrah (Rhône) is peppery and savoury; warm-climate Shiraz (Barossa) is plush and jammy. Same grape, two personalities set by climate — a clean lesson in how place shapes wine.',
          source: 'Ampelography / regional practice' },
        { id: 'g-grenache', title: 'Grenache', subtitle: 'Red · warm, sweet-fruited',
          facts: [ { label: 'Home', value: 'Southern Rhône, Spain (Garnacha)' }, { label: 'Role', value: 'The “G” in GSM blends' }, { label: 'Flavours', value: 'Strawberry, white pepper, herbs' } ],
          body: 'High in alcohol and sweet red fruit, low in colour and tannin — which is why it usually blends with structuring Syrah and Mourvèdre. The engine of Châteauneuf-du-Pape and Priorat.',
          source: 'Ampelography / regional practice' },
        { id: 'g-riesling', title: 'Riesling', subtitle: 'White · aromatic, high acid',
          facts: [ { label: 'Home', value: 'Germany, Alsace' }, { label: 'Range', value: 'Bone dry → lusciously sweet' }, { label: 'Flavours', value: 'Lime, green apple, petrol (aged)' } ],
          body: 'Arguably the finest white grape for transmitting place, with piercing acidity that balances any level of sweetness. Ages superbly, developing a distinctive kerosene note. Almost never oaked.',
          source: 'Ampelography / regional practice' },
        { id: 'g-sauvignon', title: 'Sauvignon Blanc', subtitle: 'White · zesty, herbaceous',
          facts: [ { label: 'Home', value: 'Loire (Sancerre), Bordeaux' }, { label: 'Also', value: 'Marlborough NZ' }, { label: 'Flavours', value: 'Gooseberry, grass, passionfruit' } ],
          body: 'High-acid and pungently aromatic, from flinty Sancerre to explosive Marlborough. Usually made fresh and unoaked; blended with Sémillon in Bordeaux, including sweet Sauternes.',
          source: 'Ampelography / regional practice' },
        { id: 'g-tempranillo', title: 'Tempranillo', subtitle: 'Red · savoury, medium everything',
          facts: [ { label: 'Home', value: 'Rioja, Ribera del Duero' }, { label: 'Flavours', value: 'Red plum, leather, dill (US oak)' } ],
          body: 'Spain’s noble red — moderate in acid, tannin and fruit, which makes it a canvas for oak ageing. Its savoury, leathery character deepens through the Crianza-to-Gran-Reserva ladder.',
          source: 'Ampelography / regional practice' },
        { id: 'g-malbec', title: 'Malbec', subtitle: 'Red · plush, dark, velvety',
          facts: [ { label: 'Home', value: 'Cahors (France), Mendoza (Argentina)' }, { label: 'Flavours', value: 'Black plum, violet, cocoa' } ],
          body: 'A minor Bordeaux grape reborn in high-altitude Argentina, where it makes deeply coloured, smooth, dark-fruited reds. Rustic and firm in its French home of Cahors; velvety in Mendoza.',
          source: 'Ampelography / regional practice' },
      ],
    },
  ],
};
