import type { DomainContent } from '../knowledge-core/types';

// Wine v0 — Block 1 (systematic tasting + pairing logic), the country-labelling insight,
// and classic appellation facts. All items are stable, factual, and public (appellation
// regulations / grape composition). source + verified per the accuracy gate; Simon should
// still spot-check specifics per spec 02 §3 before relying on them.
export const WINE: DomainContent = {
  id: 'wine',
  title: 'Wine',
  blurb: 'Tasting · regions · grapes',
  accent: '#7b2f3f',
  newPerDay: 6,
  // The plan targets the published topic areas of a first sommelier theory exam
  // (Court of Master Sommeliers Introductory level). Not affiliated; no exam questions —
  // the units cover the syllabus ground with verified, textbook-stable facts.
  goal: {
    title: 'Goal — Introductory Sommelier (theory)',
    blurb: 'Ten units covering the ground of a first sommelier theory exam. Work them in order — read the lessons, then the daily review drills each unit until it sticks.',
  },
  blocks: [
    {
      id: 'tasting',
      title: 'Systematic tasting',
      primer: 'Before any bottle can teach you anything, you need a fixed structure to taste against. Without one, every wine is an isolated impression you forget by the next glass.\n\nWith one, each bottle becomes a data point you can compare across regions, grapes and years. Assess the same six things, in the same order, every time.',
      lessons: [
        {
          id: 'six-axes',
          title: 'The six axes',
          diagram: '<svg viewBox="0 0 340 208" xmlns="http://www.w3.org/2000/svg" font-family="-apple-system, sans-serif">' +
            '<circle cx="18" cy="24" r="5" fill="var(--accent)"/><text x="34" y="28" font-size="14" font-weight="600" fill="var(--plat-text)">Acid</text><text x="150" y="28" font-size="12" fill="var(--plat-muted)">freshness · backbone</text>' +
            '<circle cx="18" cy="56" r="5" fill="var(--accent)"/><text x="34" y="60" font-size="14" font-weight="600" fill="var(--plat-text)">Tannin</text><text x="150" y="60" font-size="12" fill="var(--plat-muted)">grip · structure (reds)</text>' +
            '<circle cx="18" cy="88" r="5" fill="var(--accent)"/><text x="34" y="92" font-size="14" font-weight="600" fill="var(--plat-text)">Alcohol</text><text x="150" y="92" font-size="12" fill="var(--plat-muted)">warmth</text>' +
            '<circle cx="18" cy="120" r="5" fill="var(--accent)"/><text x="34" y="124" font-size="14" font-weight="600" fill="var(--plat-text)">Body</text><text x="150" y="124" font-size="12" fill="var(--plat-muted)">weight · texture</text>' +
            '<circle cx="18" cy="152" r="5" fill="var(--accent)"/><text x="34" y="156" font-size="14" font-weight="600" fill="var(--plat-text)">Fruit</text><text x="150" y="156" font-size="12" fill="var(--plat-muted)">ripeness · profile</text>' +
            '<circle cx="18" cy="184" r="5" fill="var(--accent)"/><text x="34" y="188" font-size="14" font-weight="600" fill="var(--plat-text)">Finish</text><text x="150" y="188" font-size="12" fill="var(--plat-muted)">length</text>' +
            '</svg>',
          body: 'Acid is the wine’s freshness and backbone — it makes your mouth water and keeps a wine lively. High acid feels tart and crisp; low acid feels soft, even flabby.\n\nTannin is the drying, grippy sensation on your gums, mostly in reds, from grape skins and oak. It gives structure and ageing potential.\n\nAlcohol is felt as warmth; body is the wine’s overall weight and texture — light like skim milk, or full like cream.\n\nFruit describes the ripeness and flavour family (citrus, stone fruit, red or black berry). Finish is how long the flavour lasts after you swallow — a long finish is a mark of quality.',
        },
        {
          id: 'pairing-logic',
          title: 'Pairing is logic, not lists',
          body: 'You don’t memorise pairings — you reason them from four rules.\n\nMatch acidity to fat: a high-acid wine cuts through rich, fatty food and refreshes the palate.\n\nMatch tannin to protein: tannin binds with protein and fat, so a tannic red feels smoother beside a steak than on its own.\n\nKeep the wine’s sweetness above the dish’s: a wine less sweet than the dessert tastes thin and sour.\n\nMatch weight to weight: a delicate dish is flattened by a heavy wine, and vice versa.',
        },
      ],
    },
    {
      id: 'winemaking',
      title: 'How wine is made',
      primer: 'Every fact on a label traces back to two places: the vineyard and the cellar. This unit is the machinery behind everything else — why cool places make nervy wines, why reds have tannin and whites don’t, where the butter and vanilla come from.\n\nTheory exams love this unit because it explains rather than lists: one production fact unlocks a dozen regional ones.',
      lessons: [
        { id: 'wm-vineyard', title: 'In the vineyard', body: 'Nearly all quality wine grows between roughly 30° and 50° of latitude in each hemisphere — closer to the equator is too hot, further out grapes won’t ripen.\n\nClimate sets the style before anyone touches a press: cool climates keep acidity high and alcohol moderate (Mosel, Champagne); warm climates give riper fruit, fuller body, more alcohol (Barossa, Napa). The grower’s year is a run of gambles — spring frost, summer hail, rain at harvest.\n\nOne pest reshaped everything: phylloxera, a root louse that devastated Europe’s vineyards in the late 1800s. The lasting fix is still universal practice — grafting European vines onto resistant American rootstocks.' },
        { id: 'wm-ferment', title: 'Fermentation', body: 'The engine of all wine: yeast eats grape sugar and turns it into alcohol and carbon dioxide, giving off heat. Riper grapes mean more sugar, which means more potential alcohol.\n\nThe crucial fork: red wines ferment WITH their skins — that is where all the colour and tannin come from. White wines are pressed first and ferment as clear juice. Rosé is made like a red but with only hours of skin contact before the juice runs off.\n\nTemperature is the winemaker’s throttle: cool, slow ferments preserve delicate aromatics (most whites); warmer ferments extract more from red skins.' },
        { id: 'wm-shaping', title: 'Shaping the wine', body: 'After fermentation the wine is shaped. Malolactic conversion turns sharp malic acid (green apple) into softer lactic acid (cream) — nearly every red goes through it, and it is what gives oaked Chardonnay its butter note.\n\nOak adds flavour and texture: new barrels give vanilla, spice and toast (French oak subtler and spicier; American louder — vanilla and coconut). Older barrels add little flavour but let the wine breathe slowly.\n\nLeaving a white on its dead yeast cells (the lees) builds a creamy texture — the trick behind good Muscadet and much white Burgundy.' },
      ],
    },
    {
      id: 'labelling',
      title: 'What the label tells you',
      primer: 'Here is the single most useful thing to learn about wine: every country answers “what does the label tell you?” differently.\n\nLearn each country’s organising principle and you can read a label you’ve never seen before — worth more than memorising any individual appellation.',
      lessons: [
        { id: 'lab-france', title: 'France — by place', body: 'France labels by PLACE. The grape is usually absent — a red Burgundy says “Gevrey-Chambertin”, not “Pinot Noir”, because the appellation implies the grape and style.\n\nMost French regions blend: Bordeaux (Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, Malbec), the southern Rhône (Grenache-Syrah-Mourvèdre), Champagne (Chardonnay, Pinot Noir, Meunier).\n\nThe exception is Burgundy: monovarietal (Pinot Noir or Chardonnay) yet still labelled by place. The rule holds; the blending habit doesn’t.' },
        { id: 'lab-italy', title: 'Italy — place + native grape', body: 'Italy labels by PLACE plus its NATIVE GRAPE, under the DOC/DOCG system, with enormous varietal diversity.\n\nBrunello di Montalcino is 100% Sangiovese; Barolo and Barbaresco are 100% Nebbiolo; Chianti Classico is at least 80% Sangiovese. The place tells you the rules; the grape tells you the character.' },
        { id: 'lab-spain', title: 'Spain — grape + time in oak', body: 'Spain often labels by GRAPE plus TIME IN OAK AND BOTTLE. The ladder Joven → Crianza → Reserva → Gran Reserva is an AGEING classification — not a region, and not a quality tier, a point widely misread.\n\nA Gran Reserva has simply spent the most time maturing before release.' },
        { id: 'lab-germany', title: 'Germany — grape + ripeness', body: 'Germany labels by GRAPE plus RIPENESS AT HARVEST. The Prädikat ladder — Kabinett → Spätlese → Auslese → Beerenauslese → Trockenbeerenauslese — measures must weight (sugar/ripeness when picked), not the sweetness of the finished wine.\n\nA Kabinett can be made bone dry.' },
        { id: 'lab-newworld', title: 'New World — grape first', body: 'The New World (California, Australia, Chile and the rest) labels by GRAPE first, region second — the inverse of France. “Barossa Shiraz” names the grape, then the place.\n\nIt’s the most immediately readable system, and the reason France can feel opaque by comparison.' },
      ],
    },
    {
      id: 'france',
      title: 'France in depth',
      primer: 'France is the reference point: nearly every classic grape has its benchmark here, and every region answers the theory exam’s favourite question — what grows where, and why.\n\nFour tours: Bordeaux, Burgundy (with Beaujolais), the Rhône, then the Loire and Alsace.',
      lessons: [
        { id: 'fr-bordeaux', title: 'Bordeaux', body: 'The Left Bank (Médoc, Graves — gravel soils) is Cabernet Sauvignon–led: firm, cassis-and-cedar, built to age. The Right Bank (Saint-Émilion, Pomerol — clay) is Merlot-led: rounder and plummier, approachable sooner.\n\nBlending across five permitted red grapes (Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, Malbec) hedges the uncertain Atlantic vintage.\n\nBordeaux is also white country: dry Sauvignon Blanc–Sémillon blends, and in Sauternes, botrytised sweet wines from the same pair.' },
        { id: 'fr-burgundy', title: 'Burgundy & Beaujolais', body: 'Burgundy ranks PLACES, not producers: Regional → Village → Premier Cru → Grand Cru, ever-smaller plots of Pinot Noir and Chardonnay. In the far north, Chablis makes steely, usually unoaked Chardonnay.\n\nJust south, Beaujolais is its own world: the Gamay grape, often made by carbonic maceration — whole berries fermenting from the inside — giving juicy, low-tannin reds. Ten village crus (Morgon, Fleurie…) are the serious end.' },
        { id: 'fr-rhone', title: 'The Rhône', body: 'Two Rhônes. The steep granite north grows one red grape only — Syrah (Côte-Rôtie, Hermitage): black pepper, olive, violet. Condrieu makes headily perfumed Viognier.\n\nThe wide, warm south blends: Grenache-Syrah-Mourvèdre and friends, at their grandest in Châteauneuf-du-Pape, where round galet stones store the day’s heat and radiate it back at night.' },
        { id: 'fr-loire-alsace', title: 'Loire & Alsace', body: 'Follow the Loire west to east: Muscadet at the mouth (Melon de Bourgogne, aged sur lie — the oyster wine); Chenin Blanc in the middle (Vouvray — dry, sweet or sparkling); Cabernet Franc reds (Chinon, Bourgueil); then Sauvignon Blanc at the eastern end — Sancerre and Pouilly-Fumé, flinty and precise.\n\nAlsace, across the country, breaks France’s biggest rule: it labels wine by GRAPE. Aromatic, mostly dry whites — Riesling, Gewurztraminer, Pinot Gris — with Vendanges Tardives meaning late-harvest sweet.' },
      ],
    },
    {
      id: 'italy-iberia',
      title: 'Italy, Spain & Portugal',
      primer: 'The Mediterranean core of the syllabus. Italy’s rule from the labelling unit — place plus native grape — plays out region by region; Spain adds its oak-ageing ladder; Portugal is far more than Port.',
      lessons: [
        { id: 'ii-north-italy', title: 'Northern Italy', body: 'Piedmont: Nebbiolo makes Barolo and Barbaresco — pale, tar-and-roses, fierce acid and tannin. Barbera and Dolcetto are the everyday reds; Moscato d’Asti the gently sweet fizz.\n\nVeneto: Prosecco (the Glera grape, tank method), Soave (Garganega), and the Valpolicella family — dry the grapes on mats (appassimento), then ferment fully for powerful, dry Amarone, or stop early for sweet Recioto.' },
        { id: 'ii-central-south', title: 'Central & southern Italy', body: 'Tuscany is Sangiovese: Chianti Classico (at least 80%), Brunello di Montalcino (100%, long ageing), and the “Super Tuscans” that broke the rules with Cabernet and Merlot.\n\nA classic exam trap: Vino Nobile di MONTEPULCIANO is Sangiovese from a Tuscan town; MONTEPULCIANO d’Abruzzo is a different grape that merely shares the name.\n\nThe south: Puglia’s Primitivo (genetically Zinfandel) and Sicily’s Nero d’Avola, plus fresh volcanic reds from Etna.' },
        { id: 'ii-spain', title: 'Spain', body: 'Rioja — Tempranillo softened by American oak (vanilla, dill), classified by ageing: Crianza → Reserva → Gran Reserva. Ribera del Duero grows the same grape (locally Tinto Fino) into something darker and more powerful.\n\nPriorat: old-vine Garnacha and Cariñena rooted in black slate (llicorella) — tiny yields, intense wines. Rías Baixas on the Atlantic coast makes Albariño, Spain’s zesty seafood white. Cava, the traditional-method sparkler, comes mostly from Penedès.' },
        { id: 'ii-portugal', title: 'Portugal', body: 'The Douro’s steep schist terraces grow Port — and, from the same grapes (Touriga Nacional foremost), increasingly serious dry reds.\n\nVinho Verde in the cool north is light, low in alcohol, often with a gentle spritz — drink it young. The Alentejo’s warm plains give ripe, friendly reds. And Portugal grows most of the world’s cork.' },
      ],
    },
    {
      id: 'germany-austria',
      title: 'Germany & Austria',
      primer: 'Riesling’s heartland, and the syllabus’s favourite source of label questions. The key ideas: ripeness ladders, the word for dry, and one Austrian grape to know cold.',
      lessons: [
        { id: 'ga-germany', title: 'Germany', body: 'Riesling is king: piercing acidity, low alcohol, styles from bone dry to lusciously sweet. The Prädikat ladder (Kabinett → Spätlese → Auslese → BA → TBA) measures RIPENESS AT HARVEST, not finished sweetness — and trocken on the label means dry.\n\nThe Mosel’s slate slopes give the most delicate, filigree style; Rheingau and Pfalz run riper and fuller. With age, good Riesling develops a famous petrol note — prized, not a flaw.' },
        { id: 'ga-austria', title: 'Austria', body: 'Austria is overwhelmingly a DRY-wine country. Its signature grape is Grüner Veltliner — white pepper, citrus, lentil — at its finest on the Danube terraces of the Wachau.\n\nAustrian Riesling is taut and dry; the reds to know are spicy Blaufränkisch and juicy Zweigelt.' },
      ],
    },
    {
      id: 'new-world',
      title: 'The New World',
      primer: 'Grape-first labelling, climates from foggy coast to high desert, and a shorter list of benchmarks — the exam wants region-to-grape pairs, and this unit is a run of them.',
      lessons: [
        { id: 'nw-americas', title: 'The Americas', body: 'California: Napa Cabernet is the benchmark — ripe, plush, generously oaked; cooler Sonoma leans Chardonnay and Pinot; Zinfandel is the state’s own speciality. Oregon’s Willamette Valley makes Burgundian Pinot Noir; Washington grows structured Cabernet, Merlot and Syrah.\n\nArgentina: Malbec in Mendoza, planted at 900–1,500 m — altitude keeps the freshness the heat would burn off. Chile: Cabernet from Maipo, coastal whites — and Carmenère, a Bordeaux grape lost to phylloxera and rediscovered in Chile in 1994, long mistaken for Merlot.' },
        { id: 'nw-southern', title: 'Southern hemisphere', body: 'Australia: Barossa Shiraz from some of the oldest vines on earth; Coonawarra Cabernet on terra rossa soil; bone-dry Riesling from the Clare and Eden Valleys; Margaret River Cabernet and Chardonnay.\n\nNew Zealand: Marlborough Sauvignon Blanc — the style that made a country — and Central Otago Pinot Noir, the world’s southernmost serious Pinot.\n\nSouth Africa: Stellenbosch Cabernet and Syrah, Chenin Blanc as the versatile workhorse, and Pinotage — the country’s own 1925 crossing of Pinot Noir and Cinsault.' },
      ],
    },
    {
      id: 'sparkling',
      title: 'Sparkling wines',
      primer: 'Every bubble is trapped carbon dioxide from a fermentation — the METHOD of trapping it defines the style, and method questions are exam staples.',
      lessons: [
        { id: 'sp-traditional', title: 'The traditional method', body: 'Start with a still base wine. Bottle it with a dose of yeast and sugar (liqueur de tirage); a SECOND fermentation inside that same bottle traps the CO₂.\n\nMonths or years resting on the dead yeast (lees) build the bread-and-brioche character (autolysis). Then riddling gathers the sediment into the neck, disgorgement fires it out, and the dosage tops up and sets the sweetness.\n\nUsers: Champagne, Cava, Crémant (French, outside Champagne), Franciacorta. Most Champagne is non-vintage — a house blend across years; vintage is one exceptional year.' },
        { id: 'sp-tank', title: 'Tank method & the sweetness scale', body: 'The tank (Charmat) method runs the second fermentation in a big pressurised tank instead of the bottle — cheaper, and it preserves fresh fruit and flowers. That is Prosecco’s method, on the Glera grape.\n\nThe sweetness scale, driest to sweetest: Brut Nature → Extra Brut → Brut → Extra Dry → Dry (Sec) → Demi-Sec → Doux. The famous trap: EXTRA DRY IS SWEETER THAN BRUT.' },
      ],
    },
    {
      id: 'fortified-sweet',
      title: 'Fortified & sweet wines',
      primer: 'Two roads to intensity: add spirit (fortify), or concentrate the grape’s own sugar. WHEN the spirit goes in — mid-ferment or after — decides everything, and it is the single most-asked idea in this unit.',
      lessons: [
        { id: 'fs-port-madeira', title: 'Port & Madeira', body: 'Port: grape spirit is added IN MID-FERMENT, killing the yeast while sugar remains — so Port is sweet and strong (~20%). Ruby is young and fruity; Tawny goes nutty and amber through long oxidative ageing in wood (10-, 20-year blends); Vintage Port, from one declared great year, ages for decades in bottle; LBV is the affordable single-year cousin.\n\nMadeira is deliberately heated and oxidised — which makes it nearly indestructible. Its four noble styles run driest to sweetest: Sercial → Verdelho → Bual → Malmsey.' },
        { id: 'fs-sherry', title: 'Sherry', body: 'Sherry is fortified AFTER fermentation finishes — so the base wine is bone dry. Two ageing paths: under flor, a protective film of yeast, giving pale, saline Fino (called Manzanilla when aged by the sea at Sanlúcar); or without flor, oxidatively, giving dark, nutty Oloroso. Amontillado starts under flor and finishes oxidatively.\n\nSweet Sherries are built on Pedro Ximénez (PX) — sun-dried grapes, treacle-dark. All of it moves through the solera: fractional blending across years for a consistent house style.' },
        { id: 'fs-sweet', title: 'Sweet wines', body: 'Noble rot (Botrytis cinerea) shrivels ripe grapes on the vine, concentrating sugar AND acid — the secret of Sauternes, Hungary’s Tokaji Aszú, and Germany’s BA/TBA.\n\nIce wine is pressed from grapes frozen ON THE VINE — the water stays behind as ice, the sweet essence runs. Dried-grape wines (passito) concentrate by raisining: sweet Recioto — or, fermented fully dry, Amarone.' },
      ],
    },
    {
      id: 'service',
      title: 'Service & pairing',
      primer: 'The service section of the theory exam is mostly numbers and classics: temperatures, decanting logic, and the pairings every sommelier is expected to reel off.',
      lessons: [
        { id: 'sv-temp', title: 'Temperature & glassware', body: 'Serve sparkling coldest, 6–8°C. Light whites and rosés 7–10°C; full whites 10–13°C; light reds around 13°C — lightly chilled; full reds 15–18°C.\n\n“Room temperature” for reds meant an old cellar, not a modern living room — too warm and alcohol dominates while the fruit blurs.\n\nGlassware logic: a tulip that narrows at the rim concentrates aroma; bigger bowls give big reds air; a flute keeps bubbles, though many pros prefer a white-wine glass for fine Champagne’s aroma.' },
        { id: 'sv-decant', title: 'Decanting, order, storage', body: 'Decant for two opposite reasons: OLD wine, gently, to pour it off its sediment; YOUNG tannic wine, vigorously, to soften it with air.\n\nOpen sparkling with a sigh, not a pop — ease the cork against the pressure. Taste in order: light before full, dry before sweet, and usually white before red.\n\nStore bottles cool, dark and on their side, keeping the cork moist and swollen.' },
        { id: 'sv-pairing', title: 'The classic pairings', body: 'The four rules from Unit 1 — acid cuts fat, tannin binds protein, out-sweet the dessert, weight matches weight — generate the canon:\n\nOysters with Muscadet or Chablis. Goat cheese with Sancerre. Steak with Cabernet; duck with Pinot Noir. Spicy food with an off-dry aromatic white — sugar tames heat. Stilton with Port; Roquefort with Sauternes — salt loves sweet.\n\nAnd the old adage that survives scrutiny: what grows together goes together.' },
      ],
    },
  ],
  cards: [
    // --- Block 1: systematic tasting + pairing logic ---
    { id: 'w-taste-axes', type: 'why', prompt: 'Systematic tasting fixes the things you assess in every glass. What are they?',
      explanation: 'Acid, tannin, alcohol, body, fruit, finish — a fixed structure so every bottle becomes a comparable data point rather than an anecdote.',
      source: 'Spec 03 §Wine, block 1', verified: true, tag: 'tasting', unit: 'tasting' },
    { id: 'w-taste-first', type: 'why', prompt: 'Why taste to a fixed structure from the very first bottle?',
      explanation: 'Without a structure, each subsequent bottle is an isolated impression. With one, you build a mental library you can compare across regions and vintages.',
      source: 'Spec 03 §Wine', verified: true, tag: 'tasting', unit: 'tasting' },
    { id: 'w-pair-acid', type: 'cloze', prompt: 'Pairing logic: match acidity to ___ (rich, fatty dishes).',
      answer: 'fat', accept: ['fat', 'fatty', 'richness'], explanation: 'Acid cuts through fat and refreshes the palate — think a crisp white with fried food.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing', unit: 'tasting' },
    { id: 'w-pair-tannin', type: 'cloze', prompt: 'Pairing logic: match tannin to ___ (it binds and softens against it).',
      answer: 'protein', accept: ['protein', 'proteins'], explanation: 'Tannin binds with protein and fat, so a tannic red feels smoother with a steak than on its own.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing', unit: 'tasting' },
    { id: 'w-pair-sweet', type: 'cloze', prompt: 'Pairing a dessert: the wine’s sweetness should sit ___ the dish’s sweetness.',
      answer: 'above', accept: ['above', 'higher'], explanation: 'A wine less sweet than the dessert tastes thin and sour beside it — sweet wine must out-sweet the plate.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing', unit: 'tasting' },
    { id: 'w-pair-weight', type: 'cloze', prompt: 'Pairing logic: match the ___ of the wine to the weight of the dish.',
      answer: 'weight', accept: ['weight', 'body'], explanation: 'A light dish is flattened by a heavy wine and vice versa — weight to weight, body to body.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing', unit: 'tasting' },

    // --- The structural insight the module is built on ---
    { id: 'w-label-fr-nw', type: 'why', prompt: 'Each wine country answers “what does the label tell you?” differently. What are France’s and the New World’s answers?',
      explanation: 'France labels by PLACE (appellation) — the grape is usually absent. The New World labels by GRAPE first, region second. Learning that difference is worth more than any single appellation.',
      source: 'Spec 03 §Wine, organising principle', verified: true, tag: 'labelling', unit: 'labelling' },
    { id: 'w-burgundy-exception', type: 'why', prompt: 'Burgundy is France’s exception to place-labelling. How?',
      explanation: 'It is monovarietal — Pinot Noir for reds, Chardonnay for whites — yet still labelled by PLACE, not grape. The rule (label by place) holds; the blending norm does not.',
      source: 'Spec 03 §Wine, France', verified: true, tag: 'France', unit: 'labelling' },

    // --- Classic appellation / grape facts ---
    { id: 'w-brunello', type: 'instance', prompt: 'Brunello di Montalcino is made from 100% which grape?',
      answer: 'Sangiovese', accept: ['sangiovese'], explanation: 'Brunello is 100% Sangiovese from the warmer, drier Montalcino mesoclimate, with long ageing (min. five years).',
      source: 'DOCG regulations', verified: true, tag: 'Italy', unit: 'italy-iberia' },
    { id: 'w-barolo', type: 'instance', prompt: 'Barolo and Barbaresco are made from 100% which grape?',
      answer: 'Nebbiolo', accept: ['nebbiolo'], explanation: 'Both Piedmont DOCGs are 100% Nebbiolo — high acid, high tannin, pale colour that belies its power.',
      source: 'DOCG regulations', verified: true, tag: 'Italy', unit: 'italy-iberia' },
    { id: 'w-chianti', type: 'cloze', prompt: 'Chianti Classico must be at least ___% Sangiovese.',
      answer: '80', accept: ['80', '80%'], explanation: 'Chianti Classico requires a minimum 80% Sangiovese, with the rest from permitted local or international grapes.',
      source: 'DOCG regulations', verified: true, tag: 'Italy', unit: 'italy-iberia' },
    { id: 'w-gsm', type: 'instance', prompt: 'The southern Rhône “GSM” blend is Grenache, Syrah, and ___.',
      answer: 'Mourvèdre', accept: ['mourvedre', 'mourvèdre'], explanation: 'Grenache (fruit/warmth), Syrah (structure/spice), Mourvèdre (savoury grip) — the backbone of Châteauneuf-du-Pape and much of the south.',
      source: 'Appellation practice', verified: true, tag: 'France', unit: 'france' },
    { id: 'w-bordeaux', type: 'why', prompt: 'Name the principal red grapes permitted in a classic Bordeaux blend.',
      explanation: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, and Malbec. Bordeaux blends rather than relying on one grape — the mix hedges vintage and site.',
      source: 'Appellation practice', verified: true, tag: 'France', unit: 'france' },
    { id: 'w-rioja-ladder', type: 'cloze', prompt: 'Spain’s ageing ladder: Joven → Crianza → Reserva → ___.',
      answer: 'Gran Reserva', accept: ['gran reserva', 'granreserva'], explanation: 'Each step requires more time in oak and bottle before release.',
      source: 'Spanish DO ageing rules', verified: true, tag: 'Spain', unit: 'italy-iberia' },
    { id: 'w-rioja-meaning', type: 'why', prompt: 'In Spain, what do Crianza / Reserva / Gran Reserva classify — and what is it commonly misread as?',
      explanation: 'They classify TIME IN OAK AND BOTTLE (ageing), not the region or inherent quality. It is widely misread as a quality or origin tier — it is an ageing scale.',
      source: 'Spec 03 §Wine, Spain', verified: true, tag: 'Spain', unit: 'italy-iberia' },
    { id: 'w-pradikat', type: 'cloze', prompt: 'Germany’s Prädikat ripeness ladder: Kabinett → Spätlese → Auslese → BA → ___.',
      answer: 'TBA', accept: ['tba', 'trockenbeerenauslese'], explanation: 'Trockenbeerenauslese (TBA) — from individually selected botrytised, shrivelled berries.',
      source: 'German wine law', verified: true, tag: 'Germany', unit: 'germany-austria' },
    { id: 'w-pradikat-meaning', type: 'why', prompt: 'German Prädikat levels (Kabinett…TBA) measure what, exactly?',
      explanation: 'Must weight — the sugar/ripeness of the grapes AT HARVEST — not the sweetness of the finished wine. A Kabinett can be made bone dry.',
      source: 'Spec 03 §Wine, Germany', verified: true, tag: 'Germany', unit: 'germany-austria' },
    { id: 'w-champagne', type: 'instance', prompt: 'Champagne’s three principal grapes are Chardonnay, Pinot Noir, and ___.',
      answer: 'Meunier', accept: ['meunier', 'pinot meunier'], explanation: 'Meunier adds fruit and approachability; Chardonnay finesse; Pinot Noir structure.',
      source: 'Appellation practice', verified: true, tag: 'Champagne', unit: 'sparkling' },

    // --- Unit 2: How wine is made ---
    { id: 'w-wm-yeast', type: 'cloze', prompt: 'Fermentation: yeast turns grape sugar into alcohol and ___.',
      answer: 'CO2', accept: ['co2', 'carbon dioxide', 'co₂'], explanation: 'Sugar → alcohol + carbon dioxide (+ heat). Riper grapes carry more sugar, so more potential alcohol.',
      source: 'Production method — standard reference', verified: true, tag: 'winemaking', unit: 'winemaking' },
    { id: 'w-wm-skins', type: 'why', prompt: 'Where do a red wine’s colour and tannin come from?',
      explanation: 'The grape SKINS, during fermentation — reds ferment with them, whites are pressed off first. That single fork explains most of the red/white difference.',
      source: 'Production method — standard reference', verified: true, tag: 'winemaking', unit: 'winemaking' },
    { id: 'w-wm-lat', type: 'cloze', prompt: 'Most quality vineyards lie between roughly ___° and 50° of latitude.',
      answer: '30', accept: ['30', '30°'], explanation: 'The 30–50° bands in each hemisphere: closer to the equator is too hot, further out grapes won’t ripen.',
      source: 'Viticulture — standard reference', verified: true, tag: 'winemaking', unit: 'winemaking' },
    { id: 'w-wm-phylloxera', type: 'why', prompt: 'What is phylloxera, and what is the lasting fix?',
      explanation: 'A root louse that devastated Europe’s vineyards in the late 1800s. The fix — still universal — is grafting European vines onto resistant American rootstocks.',
      source: 'Viticulture — standard reference', verified: true, tag: 'winemaking', unit: 'winemaking' },
    { id: 'w-wm-malo', type: 'cloze', prompt: 'Malolactic conversion turns sharp malic acid into softer ___ acid.',
      answer: 'lactic', accept: ['lactic'], explanation: 'Green-apple malic → creamy lactic. Nearly all reds go through it; it gives oaked Chardonnay its butter note.',
      source: 'Production method — standard reference', verified: true, tag: 'winemaking', unit: 'winemaking' },
    { id: 'w-wm-oak', type: 'why', prompt: 'What does NEW oak give a wine that old barrels don’t?',
      explanation: 'Flavour — vanilla, spice, toast (French oak subtler, American louder). Older barrels add little flavour; they mainly let the wine breathe slowly.',
      source: 'Production method — standard reference', verified: true, tag: 'winemaking', unit: 'winemaking' },
    { id: 'w-wm-cool', type: 'cloze', prompt: 'Cool climates give wines higher ___ and lower alcohol.',
      answer: 'acidity', accept: ['acidity', 'acid'], explanation: 'Cool = high acid, moderate alcohol (Mosel, Champagne). Warm = riper, fuller, more alcohol (Barossa, Napa).',
      source: 'Viticulture — standard reference', verified: true, tag: 'winemaking', unit: 'winemaking' },
    { id: 'w-wm-rose', type: 'why', prompt: 'How is most rosé made?',
      explanation: 'Like a red but with only hours of skin contact before the juice runs off. Blending red and white is not the norm for still wine — sparkling rosé (Champagne) is the famous exception.',
      source: 'Production method — standard reference', verified: true, tag: 'winemaking', unit: 'winemaking' },

    // --- Unit 4: France additions ---
    { id: 'w-fr-sancerre', type: 'instance', prompt: 'White Sancerre and Pouilly-Fumé are made from which grape?',
      answer: 'Sauvignon Blanc', accept: ['sauvignon blanc', 'sauvignon'], explanation: 'The eastern Loire’s flinty, precise Sauvignon Blanc — the Old World benchmark for the grape.',
      source: 'Appellation regulation', verified: true, tag: 'France', unit: 'france' },
    { id: 'w-fr-vouvray', type: 'instance', prompt: 'Vouvray (Loire) is made from which grape?',
      answer: 'Chenin Blanc', accept: ['chenin blanc', 'chenin'], explanation: 'Loire Chenin Blanc — dry, sweet or sparkling from the same appellation, always with racy acidity.',
      source: 'Appellation regulation', verified: true, tag: 'France', unit: 'france' },
    { id: 'w-fr-muscadet', type: 'instance', prompt: 'Muscadet — the oyster wine — is made from which grape?',
      answer: 'Melon de Bourgogne', accept: ['melon de bourgogne', 'melon'], explanation: 'Melon de Bourgogne at the Loire’s Atlantic mouth, often aged sur lie for texture. Born for shellfish.',
      source: 'Appellation regulation', verified: true, tag: 'France', unit: 'france' },
    { id: 'w-fr-chinon', type: 'instance', prompt: 'Chinon and Bourgueil reds are made from which grape?',
      answer: 'Cabernet Franc', accept: ['cabernet franc', 'cab franc'], explanation: 'The middle Loire’s red: Cabernet Franc — raspberry, pencil shavings, a leafy freshness.',
      source: 'Appellation regulation', verified: true, tag: 'France', unit: 'france' },
    { id: 'w-fr-alsace', type: 'why', prompt: 'Which French labelling rule does Alsace break?',
      explanation: 'It labels by GRAPE (Riesling, Gewurztraminer, Pinot Gris) — the one French region on the New World system. Mostly dry, aromatic whites; Vendanges Tardives = late-harvest sweet.',
      source: 'Appellation regulation', verified: true, tag: 'France', unit: 'france' },
    { id: 'w-fr-gamay', type: 'instance', prompt: 'Beaujolais is made from which grape?',
      answer: 'Gamay', accept: ['gamay'], explanation: 'Gamay, often via carbonic maceration — juicy, low-tannin reds; the ten crus (Morgon, Fleurie…) are the serious end.',
      source: 'Appellation regulation', verified: true, tag: 'France', unit: 'france' },
    { id: 'w-fr-chablis', type: 'cloze', prompt: 'Chablis is 100% ___ — steely and usually unoaked.',
      answer: 'Chardonnay', accept: ['chardonnay'], explanation: 'Burgundy’s cool northern outpost: pure Chardonnay, lean, mineral, mostly without new oak.',
      source: 'Appellation regulation', verified: true, tag: 'France', unit: 'france' },

    // --- Unit 5: Italy & Iberia additions ---
    { id: 'w-ii-amarone', type: 'why', prompt: 'Amarone is both powerful AND dry — how?',
      explanation: 'The grapes are dried first (appassimento), concentrating sugar — then fermented fully dry, so the sugar becomes power (15%+ alcohol). Stop the ferment early instead and you get sweet Recioto.',
      source: 'Production method — standard reference', verified: true, tag: 'Italy', unit: 'italy-iberia' },
    { id: 'w-ii-albarino', type: 'instance', prompt: 'Rías Baixas (Spain) is famous for which white grape?',
      answer: 'Albariño', accept: ['albarino', 'albariño'], explanation: 'Atlantic-coast Albariño — peachy, saline, Spain’s seafood white.',
      source: 'DO regulation', verified: true, tag: 'Spain', unit: 'italy-iberia' },
    { id: 'w-ii-ribera', type: 'instance', prompt: 'Ribera del Duero’s red grape (locally “Tinto Fino”)?',
      answer: 'Tempranillo', accept: ['tempranillo', 'tinto fino'], explanation: 'The same grape as Rioja, grown higher and hotter-by-day — darker, more powerful wines.',
      source: 'DO regulation', verified: true, tag: 'Spain', unit: 'italy-iberia' },
    { id: 'w-ii-priorat', type: 'instance', prompt: 'Priorat’s leading grape, from old vines on black slate?',
      answer: 'Garnacha', accept: ['garnacha', 'grenache'], explanation: 'Old-vine Garnacha (with Cariñena) rooted in llicorella slate — tiny yields, intense wines.',
      source: 'DOQ regulation', verified: true, tag: 'Spain', unit: 'italy-iberia' },
    { id: 'w-ii-nero', type: 'instance', prompt: 'Sicily’s flagship red grape?',
      answer: 'Nero d’Avola', accept: ['nero davola', 'nero d avola', 'nero d’avola', "nero d'avola"], explanation: 'Dark, plummy Nero d’Avola — plus fresh volcanic reds from Etna as the island’s modern face.',
      source: 'Regional fact — standard reference', verified: true, tag: 'Italy', unit: 'italy-iberia' },
    { id: 'w-ii-primitivo', type: 'instance', prompt: 'Puglia’s Primitivo is genetically the same grape as California’s ___.',
      answer: 'Zinfandel', accept: ['zinfandel', 'zin'], explanation: 'DNA testing proved Primitivo and Zinfandel are the same Croatian-born variety — one grape, two hemispheres of style.',
      source: 'Ampelography (DNA-established)', verified: true, tag: 'Italy', unit: 'italy-iberia' },

    // --- Unit 6: Germany & Austria ---
    { id: 'w-ga-gruner', type: 'instance', prompt: 'Austria’s signature white grape?',
      answer: 'Grüner Veltliner', accept: ['gruner veltliner', 'grüner veltliner', 'gruner'], explanation: 'White pepper, citrus, lentil — at its finest on the Danube terraces of the Wachau.',
      source: 'Regional fact — standard reference', verified: true, tag: 'Austria', unit: 'germany-austria' },
    { id: 'w-ga-trocken', type: 'cloze', prompt: 'The German label word for “dry”: ___.',
      answer: 'trocken', accept: ['trocken'], explanation: 'Trocken = dry. Crucial because the Prädikat ladder measures ripeness at harvest, not finished sweetness.',
      source: 'German wine law', verified: true, tag: 'Germany', unit: 'germany-austria' },
    { id: 'w-ga-mosel', type: 'cloze', prompt: 'Mosel Riesling is famously high in acid and low in ___.',
      answer: 'alcohol', accept: ['alcohol'], explanation: 'Often just 8–9% — slate slopes, cool climate, filigree wines balanced by a touch of sweetness.',
      source: 'Regional fact — standard reference', verified: true, tag: 'Germany', unit: 'germany-austria' },
    { id: 'w-ga-petrol', type: 'why', prompt: 'The telltale aroma of maturing Riesling?',
      explanation: 'A petrol/kerosene note — prized by lovers of aged Riesling, not a flaw.',
      source: 'Tasting — standard reference', verified: true, tag: 'Germany', unit: 'germany-austria' },
    { id: 'w-ga-wachau', type: 'instance', prompt: 'Austria’s famous Danube wine valley?',
      answer: 'Wachau', accept: ['wachau'], explanation: 'Steep terraces over the Danube — benchmark Grüner Veltliner and dry Riesling.',
      source: 'Regional fact — standard reference', verified: true, tag: 'Austria', unit: 'germany-austria' },

    // --- Unit 7: The New World ---
    { id: 'w-nw-carmenere', type: 'instance', prompt: 'Chile’s rediscovered Bordeaux grape, long mistaken for Merlot?',
      answer: 'Carmenère', accept: ['carmenere', 'carmenère'], explanation: 'Lost to Europe with phylloxera, identified in Chilean “Merlot” vineyards in 1994 — now Chile’s signature red.',
      source: 'Ampelography (DNA-established)', verified: true, tag: 'Chile', unit: 'new-world' },
    { id: 'w-nw-mendoza', type: 'cloze', prompt: 'Mendoza Malbec keeps its freshness thanks to vineyard ___.',
      answer: 'altitude', accept: ['altitude', 'elevation', 'height'], explanation: '900–1,500 m in the Andes foothills: intense sun by day, cool nights that preserve acidity.',
      source: 'Regional fact — standard reference', verified: true, tag: 'Argentina', unit: 'new-world' },
    { id: 'w-nw-willamette', type: 'instance', prompt: 'Oregon’s Willamette Valley signature grape?',
      answer: 'Pinot Noir', accept: ['pinot noir', 'pinot'], explanation: 'Cool and rainy — the Burgundian answer to California, bright and red-fruited.',
      source: 'Regional fact — standard reference', verified: true, tag: 'USA', unit: 'new-world' },
    { id: 'w-nw-coonawarra', type: 'instance', prompt: 'Coonawarra’s terra rossa soil is famous for which grape?',
      answer: 'Cabernet Sauvignon', accept: ['cabernet sauvignon', 'cabernet', 'cab sauv'], explanation: 'A narrow strip of iron-red soil over limestone — Australia’s classic Cabernet terroir.',
      source: 'Regional fact — standard reference', verified: true, tag: 'Australia', unit: 'new-world' },
    { id: 'w-nw-marlborough', type: 'instance', prompt: 'Marlborough (New Zealand) made its name with which grape?',
      answer: 'Sauvignon Blanc', accept: ['sauvignon blanc', 'sauvignon'], explanation: 'Explosive passionfruit-and-gooseberry Sauvignon Blanc — a style so distinctive it built an industry.',
      source: 'Regional fact — standard reference', verified: true, tag: 'New Zealand', unit: 'new-world' },
    { id: 'w-nw-pinotage', type: 'why', prompt: 'What is Pinotage?',
      explanation: 'South Africa’s own grape: a 1925 crossing of Pinot Noir × Cinsault. Dark, smoky, and divisive — but unmistakably South African.',
      source: 'Ampelography', verified: true, tag: 'South Africa', unit: 'new-world' },
    { id: 'w-nw-clare', type: 'cloze', prompt: 'Australia’s Clare and Eden Valleys are famous for bone-dry ___.',
      answer: 'Riesling', accept: ['riesling'], explanation: 'Lime-zest, steely dry Riesling that ages superbly — Australia’s great white secret.',
      source: 'Regional fact — standard reference', verified: true, tag: 'Australia', unit: 'new-world' },

    // --- Unit 8: Sparkling ---
    { id: 'w-sp-trad', type: 'why', prompt: 'In the traditional method, where do the bubbles come from?',
      explanation: 'A SECOND fermentation inside the final bottle (started by the liqueur de tirage) — the CO₂ has nowhere to go. Champagne, Cava, Crémant, Franciacorta all work this way.',
      source: 'Production method — standard reference', verified: true, tag: 'sparkling', unit: 'sparkling' },
    { id: 'w-sp-lees', type: 'cloze', prompt: 'Champagne’s bready, brioche character comes from long ageing on the ___.',
      answer: 'lees', accept: ['lees'], explanation: 'The dead yeast from the second fermentation — autolysis is the flavour signature of the traditional method.',
      source: 'Production method — standard reference', verified: true, tag: 'sparkling', unit: 'sparkling' },
    { id: 'w-sp-prosecco', type: 'cloze', prompt: 'Prosecco gets its bubbles from the ___ method.',
      answer: 'tank', accept: ['tank', 'charmat'], explanation: 'Second fermentation in a pressurised tank — cheaper, and it keeps the fresh fruit-and-flower style.',
      source: 'Production method — standard reference', verified: true, tag: 'sparkling', unit: 'sparkling' },
    { id: 'w-sp-glera', type: 'instance', prompt: 'Prosecco is made from which grape?',
      answer: 'Glera', accept: ['glera'], explanation: 'Glera, in the Veneto — tank-method, fresh and floral.',
      source: 'DOC regulation', verified: true, tag: 'sparkling', unit: 'sparkling' },
    { id: 'w-sp-brut', type: 'why', prompt: 'Brut vs Extra Dry — which is drier?',
      explanation: 'BRUT. The scale runs Brut Nature → Extra Brut → Brut → Extra Dry → Dry → Demi-Sec → Doux, so “Extra Dry” is actually sweeter than Brut — the classic label trap.',
      source: 'EU labelling scale', verified: true, tag: 'sparkling', unit: 'sparkling' },
    { id: 'w-sp-cava', type: 'instance', prompt: 'Spain’s traditional-method sparkling wine is called ___.',
      answer: 'Cava', accept: ['cava'], explanation: 'Mostly from Penedès — same in-bottle second fermentation as Champagne.',
      source: 'DO regulation', verified: true, tag: 'sparkling', unit: 'sparkling' },
    { id: 'w-sp-cremant', type: 'cloze', prompt: 'French traditional-method fizz made outside Champagne is labelled ___.',
      answer: 'Crémant', accept: ['cremant', 'crémant'], explanation: 'Crémant d’Alsace, de Loire, de Bourgogne… same method, different address, friendlier price.',
      source: 'Appellation regulation', verified: true, tag: 'sparkling', unit: 'sparkling' },

    // --- Unit 9: Fortified & sweet ---
    { id: 'w-fs-port', type: 'why', prompt: 'Why is Port sweet?',
      explanation: 'Grape spirit is added IN MID-FERMENT — it kills the yeast while sugar remains, leaving the wine sweet and strong (~20%).',
      source: 'Production method — standard reference', verified: true, tag: 'fortified', unit: 'fortified-sweet' },
    { id: 'w-fs-sherry', type: 'why', prompt: 'Why is a base Sherry bone dry?',
      explanation: 'It is fortified AFTER fermentation has finished — all the sugar is already gone. The Port/Sherry timing contrast is the most-asked idea in fortified wine.',
      source: 'Production method — standard reference', verified: true, tag: 'fortified', unit: 'fortified-sweet' },
    { id: 'w-fs-flor', type: 'cloze', prompt: 'The protective film of yeast on a Fino Sherry is called ___.',
      answer: 'flor', accept: ['flor'], explanation: 'Flor shields the wine from oxygen — keeping Fino pale, fresh and saline.',
      source: 'DO Jerez practice', verified: true, tag: 'fortified', unit: 'fortified-sweet' },
    { id: 'w-fs-manzanilla', type: 'instance', prompt: 'Fino-style Sherry aged by the sea at Sanlúcar is called ___.',
      answer: 'Manzanilla', accept: ['manzanilla'], explanation: 'Same biological ageing under flor, but the coastal air of Sanlúcar de Barrameda — the most delicate, saline style.',
      source: 'DO regulation', verified: true, tag: 'fortified', unit: 'fortified-sweet' },
    { id: 'w-fs-oloroso', type: 'cloze', prompt: 'Dark, nutty Sherry aged oxidatively — without flor — is called ___.',
      answer: 'Oloroso', accept: ['oloroso'], explanation: 'Fortified higher so no flor survives; oxygen builds walnut and dried-fruit depth. Amontillado starts under flor, then finishes this way.',
      source: 'DO Jerez practice', verified: true, tag: 'fortified', unit: 'fortified-sweet' },
    { id: 'w-fs-tawny', type: 'why', prompt: 'What makes Tawny Port tawny?',
      explanation: 'Long OXIDATIVE ageing in wood — colour fades to amber while nutty, dried-fruit flavours build (10- and 20-year blends). Ruby stays young and fruity; Vintage ages in bottle instead.',
      source: 'Production method — standard reference', verified: true, tag: 'fortified', unit: 'fortified-sweet' },
    { id: 'w-fs-madeira', type: 'cloze', prompt: 'Madeira’s styles, driest to sweetest: Sercial, Verdelho, Bual, ___.',
      answer: 'Malmsey', accept: ['malmsey', 'malvasia'], explanation: 'The four noble varieties in sweetness order. Deliberate heating and oxidation make Madeira nearly indestructible.',
      source: 'Regional practice', verified: true, tag: 'fortified', unit: 'fortified-sweet' },
    { id: 'w-fs-botrytis', type: 'why', prompt: 'What is noble rot, and why is it prized?',
      explanation: 'Botrytis cinerea shrivels ripe grapes on the vine, concentrating sugar AND acid — the engine of Sauternes, Tokaji Aszú and Germany’s BA/TBA.',
      source: 'Production method — standard reference', verified: true, tag: 'sweet', unit: 'fortified-sweet' },
    { id: 'w-fs-eiswein', type: 'cloze', prompt: 'Ice wine is pressed from grapes frozen ___.',
      answer: 'on the vine', accept: ['on the vine', 'onthevine', 'on vine'], explanation: 'Pressed while frozen: the water stays behind as ice and only the sweet essence runs — Eiswein in Germany, icewine in Canada.',
      source: 'Production method — standard reference', verified: true, tag: 'sweet', unit: 'fortified-sweet' },

    // --- Unit 10: Service & pairing ---
    { id: 'w-sv-red-temp', type: 'why', prompt: 'Why not serve big reds at modern “room temperature”?',
      explanation: 'The old rule meant a cellar — 15–18°C. In a warm living room the alcohol dominates and the fruit blurs; many reds improve with 20 minutes in the fridge.',
      source: 'Classic service standard', verified: true, tag: 'service', unit: 'service' },
    { id: 'w-sv-spark-temp', type: 'cloze', prompt: 'Sparkling wine is served coldest of all: ___–8°C.',
      answer: '6', accept: ['6', '6°', '6c'], explanation: 'Cold keeps the mousse fine and the acidity refreshing. Whites 7–13°C by weight; light reds ~13°C; full reds 15–18°C.',
      source: 'Classic service standard', verified: true, tag: 'service', unit: 'service' },
    { id: 'w-sv-decant', type: 'why', prompt: 'Name the two different reasons to decant.',
      explanation: 'OLD wine: gently, to pour it off its sediment. YOUNG tannic wine: vigorously, to soften it with air. Same tool, opposite intentions.',
      source: 'Classic service standard', verified: true, tag: 'service', unit: 'service' },
    { id: 'w-sv-roquefort', type: 'why', prompt: 'The canonical partner for Roquefort?',
      explanation: 'Sauternes — salt loves sweet, and the wine’s botrytis richness stands up to the blue. The template for all sweet-wine-and-blue-cheese pairings.',
      source: 'Classic pairing canon', verified: true, tag: 'service', unit: 'service' },
    { id: 'w-sv-stilton', type: 'why', prompt: 'The canonical partner for Stilton?',
      explanation: 'Port — the other great sweet-versus-salty-blue marriage, and a fixture of the sommelier canon.',
      source: 'Classic pairing canon', verified: true, tag: 'service', unit: 'service' },
    { id: 'w-sv-spice', type: 'why', prompt: 'Best wine style for genuinely spicy food?',
      explanation: 'An off-dry aromatic white — Riesling or Gewurztraminer. A little sugar tames the heat, and low alcohol avoids amplifying the burn (high-alcohol tannic reds do the opposite).',
      source: 'Classic pairing canon', verified: true, tag: 'service', unit: 'service' },
    { id: 'w-sv-order', type: 'cloze', prompt: 'Tasting order: light before full, dry before ___.',
      answer: 'sweet', accept: ['sweet'], explanation: 'Sweet first would flatten everything after it; likewise a blockbuster red before a delicate white.',
      source: 'Classic service standard', verified: true, tag: 'service', unit: 'service' },
  ],

  // Equirectangular pins (x = lon+180, y = 90−lat) over the real Natural Earth outlines.
  // `country` lights up the home country on each entry's zoomed regional map.
  mapPins: [
    { entryId: 'r-bordeaux', label: 'Bordeaux', x: 179.4, y: 45.2, country: 'France' },
    { entryId: 'r-burgundy', label: 'Burgundy', x: 184.8, y: 42.9, country: 'France' },
    { entryId: 'r-champagne', label: 'Champagne', x: 184.0, y: 41.0, country: 'France' },
    { entryId: 'r-rhone', label: 'Rhône', x: 184.8, y: 45.3, country: 'France' },
    { entryId: 'r-loire', label: 'Loire', x: 180.4, y: 42.6, country: 'France' },
    { entryId: 'r-alsace', label: 'Alsace', x: 187.4, y: 41.9, country: 'France' },
    { entryId: 'r-provence', label: 'Provence', x: 186.0, y: 46.5, country: 'France' },
    { entryId: 'r-piedmont', label: 'Piedmont', x: 188.0, y: 45.3, country: 'Italy' },
    { entryId: 'r-veneto', label: 'Veneto', x: 190.9, y: 44.5, country: 'Italy' },
    { entryId: 'r-tuscany', label: 'Tuscany', x: 191.2, y: 46.6, country: 'Italy' },
    { entryId: 'r-sicily', label: 'Sicily', x: 195.0, y: 52.3, country: 'Italy' },
    { entryId: 'r-rioja', label: 'Rioja', x: 177.4, y: 47.5, country: 'Spain' },
    { entryId: 'r-riasbaixas', label: 'Rías Baixas', x: 171.4, y: 47.6, country: 'Spain' },
    { entryId: 'r-ribera', label: 'Ribera del Duero', x: 176.3, y: 48.4, country: 'Spain' },
    { entryId: 'r-priorat', label: 'Priorat', x: 180.8, y: 48.8, country: 'Spain' },
    { entryId: 'r-jerez', label: 'Jerez (Sherry)', x: 173.9, y: 53.3, country: 'Spain' },
    { entryId: 'r-douro', label: 'Douro', x: 172.5, y: 48.9, country: 'Portugal' },
    { entryId: 'r-mosel', label: 'Mosel', x: 187.0, y: 40.1, country: 'Germany' },
    { entryId: 'r-wachau', label: 'Wachau', x: 195.4, y: 41.6, country: 'Austria' },
    { entryId: 'r-tokaj', label: 'Tokaj', x: 201.4, y: 41.9, country: 'Hungary' },
    { entryId: 'r-napa', label: 'Napa', x: 57.7, y: 51.6, country: 'United States of America' },
    { entryId: 'r-sonoma', label: 'Sonoma', x: 57.1, y: 51.5, country: 'United States of America' },
    { entryId: 'r-willamette', label: 'Willamette', x: 56.9, y: 45.0, country: 'United States of America' },
    { entryId: 'r-mendoza', label: 'Mendoza', x: 111.2, y: 122.8, country: 'Argentina' },
    { entryId: 'r-maipo', label: 'Maipo', x: 109.2, y: 123.5, country: 'Chile' },
    { entryId: 'r-barossa', label: 'Barossa', x: 318.9, y: 124.5, country: 'Australia' },
    { entryId: 'r-coonawarra', label: 'Coonawarra', x: 320.8, y: 127.3, country: 'Australia' },
    { entryId: 'r-margaret', label: 'Margaret River', x: 295.1, y: 123.9, country: 'Australia' },
    { entryId: 'r-marlborough', label: 'Marlborough', x: 353.9, y: 131.5, country: 'New Zealand' },
    { entryId: 'r-otago', label: 'Central Otago', x: 349.2, y: 135.0, country: 'New Zealand' },
    { entryId: 'r-stellenbosch', label: 'Stellenbosch', x: 198.9, y: 124.0, country: 'South Africa' },
  ],

  explore: [
    {
      id: 'regions',
      title: 'Anchor regions',
      blurb: 'Tap a pin on the map, or a card below. Each is a one-pager you can read in a minute.',
      kind: 'gallery',
      entries: [
        { id: 'r-bordeaux', title: 'Bordeaux', subtitle: 'France · Cabernet/Merlot blends',
          facts: [ { label: 'Country', value: 'France' }, { label: 'Signature', value: 'Cab. Sauvignon, Merlot' }, { label: 'Style', value: 'Structured, age-worthy reds' }, { label: 'Split', value: 'Left Bank (Cab) vs Right Bank (Merlot)' } ],
          body: 'Bordeaux is the reference point for blended reds. The Left Bank (Médoc, Graves) is Cabernet Sauvignon–led — firm tannin, cassis, cedar, built to age. The Right Bank (Saint-Émilion, Pomerol) is Merlot-led — rounder, plummier, approachable younger.\n\nBlending across five permitted grapes (Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, Malbec) is the whole point: it hedges an uncertain maritime vintage and site. It also makes sweet whites in Sauternes from botrytised Sémillon and Sauvignon Blanc.',
          source: 'Appellation regulations' },
        { id: 'r-burgundy', title: 'Burgundy', subtitle: 'France · Pinot Noir & Chardonnay',
          facts: [ { label: 'Country', value: 'France' }, { label: 'Reds', value: 'Pinot Noir' }, { label: 'Whites', value: 'Chardonnay' }, { label: 'Logic', value: 'Single grape, labelled by place' } ],
          body: 'Burgundy is the great exception: monovarietal wines still labelled by PLACE, not grape. A hierarchy of ever-smaller plots — regional → village → Premier Cru → Grand Cru — expresses the belief that the vineyard, not the winemaker, is the author.\n\nReds are Pinot Noir (perfumed, red-fruited, translucent); whites are Chardonnay (from steely Chablis in the north to rich Meursault in the Côte de Beaune).',
          source: 'Appellation regulations' },
        { id: 'r-champagne', title: 'Champagne', subtitle: 'France · traditional-method sparkling',
          facts: [ { label: 'Country', value: 'France' }, { label: 'Grapes', value: 'Chardonnay, Pinot Noir, Meunier' }, { label: 'Method', value: 'Second fermentation in bottle' }, { label: 'Note', value: 'A place, not just a style' } ],
          body: 'Champagne is a cool northern region whose bubbles come from a second fermentation IN the bottle (the traditional method), which traps CO₂ and builds the fine, persistent mousse and bready autolytic character.\n\n“Blanc de Blancs” is 100% Chardonnay; “Blanc de Noirs” is from the black grapes (Pinot Noir, Meunier) pressed pale. Most Champagne is non-vintage — a house blend across years for consistency.',
          source: 'Appellation practice' },
        { id: 'r-rhone', title: 'Rhône Valley', subtitle: 'France · Syrah (north) · GSM (south)',
          facts: [ { label: 'Country', value: 'France' }, { label: 'North', value: '100% Syrah (Côte-Rôtie, Hermitage)' }, { label: 'South', value: 'GSM blends (Châteauneuf-du-Pape)' }, { label: 'Style', value: 'Peppery to warm & spicy' } ],
          body: 'Two Rhônes. The steep northern Rhône is Syrah — black pepper, olive, violets — sometimes co-fermented with a splash of white Viognier in Côte-Rôtie.\n\nThe warmer, flatter south is blend country: Grenache-Syrah-Mourvèdre (GSM) plus more, over the galets (large round stones) of Châteauneuf-du-Pape, which store heat and reflect it into the vines.',
          source: 'Appellation practice' },
        { id: 'r-piedmont', title: 'Piedmont', subtitle: 'Italy · Nebbiolo',
          facts: [ { label: 'Country', value: 'Italy' }, { label: 'Grape', value: '100% Nebbiolo (Barolo, Barbaresco)' }, { label: 'Profile', value: 'Pale colour, high acid & tannin' }, { label: 'Also', value: 'Barbera, Dolcetto, Moscato' } ],
          body: 'Piedmont’s Barolo and Barbaresco are 100% Nebbiolo — deceptively pale and light-looking, yet fiercely tannic, high in acid, and long-lived, with tar-and-roses aromatics.\n\nEveryday drinking comes from juicy Barbera and soft Dolcetto; sweet, gently fizzy Moscato d’Asti is the region’s famous low-alcohol white.',
          source: 'DOCG regulations' },
        { id: 'r-tuscany', title: 'Tuscany', subtitle: 'Italy · Sangiovese',
          facts: [ { label: 'Country', value: 'Italy' }, { label: 'Grape', value: 'Sangiovese' }, { label: 'Wines', value: 'Chianti Classico, Brunello di Montalcino' }, { label: 'Also', value: '“Super Tuscans” (Bordeaux blends)' } ],
          body: 'Sangiovese rules Tuscany: sour-cherry fruit, savoury herbs, brisk acidity. Chianti Classico is ≥80% Sangiovese; Brunello di Montalcino is 100% Sangiovese from a warmer site with long ageing (min. five years).\n\nThe “Super Tuscans” broke the old rules in the 1970s by blending in Cabernet and Merlot — initially sold as humble table wine, now among Italy’s most prized.',
          source: 'DOCG regulations' },
        { id: 'r-rioja', title: 'Rioja', subtitle: 'Spain · Tempranillo',
          facts: [ { label: 'Country', value: 'Spain' }, { label: 'Grape', value: 'Tempranillo (+ Garnacha)' }, { label: 'Ladder', value: 'Joven → Crianza → Reserva → Gran Reserva' }, { label: 'Signature', value: 'American-oak vanilla & dill' } ],
          body: 'Rioja is Tempranillo country, traditionally married to American oak that lends a signature vanilla, coconut and dill note. The label’s Crianza/Reserva/Gran Reserva ladder measures TIME IN OAK AND BOTTLE — not quality or origin.\n\nA Gran Reserva is released only after years of ageing, arriving mellow and savoury; a Joven is unoaked and fruity.',
          source: 'Spanish DO rules' },
        { id: 'r-douro', title: 'Douro', subtitle: 'Portugal · Port & dry reds',
          facts: [ { label: 'Country', value: 'Portugal' }, { label: 'Grapes', value: 'Touriga Nacional & field blends' }, { label: 'Famous for', value: 'Port (fortified)' }, { label: 'Terrain', value: 'Steep schist terraces' } ],
          body: 'The Douro’s steep schist terraces gave the world Port — a red fortified by adding grape spirit mid-fermentation, which stops the yeast and leaves the wine sweet and strong.\n\nThe same indigenous grapes (Touriga Nacional foremost) now make serious dry reds, powerful and floral, that put the region on the fine-wine map beyond fortifieds.',
          source: 'Regional practice' },
        { id: 'r-mosel', title: 'Mosel', subtitle: 'Germany · Riesling',
          facts: [ { label: 'Country', value: 'Germany' }, { label: 'Grape', value: 'Riesling' }, { label: 'Style', value: 'Low alcohol, high acid, off-dry to sweet' }, { label: 'Ladder', value: 'Prädikat = ripeness at harvest' } ],
          body: 'The Mosel’s slate slopes make some of the world’s most delicate Rieslings — often just 8–9% alcohol, with racing acidity balanced by a touch of sweetness, and an unmistakable “petrol” note with age.\n\nThe Prädikat ladder (Kabinett → Spätlese → Auslese → BA → TBA) grades the grapes’ ripeness AT HARVEST, not the finished sweetness: a Kabinett can be bone dry (“trocken”).',
          source: 'German wine law' },
        { id: 'r-napa', title: 'Napa Valley', subtitle: 'USA · Cabernet Sauvignon',
          facts: [ { label: 'Country', value: 'USA (California)' }, { label: 'Grape', value: 'Cabernet Sauvignon' }, { label: 'Style', value: 'Ripe, full-bodied, generous oak' }, { label: 'Labelled by', value: 'Grape first (New World)' } ],
          body: 'Napa is the New World’s Cabernet benchmark: warm days and cool nights give ripe, plush, high-alcohol reds with cassis and vanilla-toast oak. Hillside sites (Howell Mountain) add structure; valley floor gives opulence.\n\nLike the rest of the New World, it labels by grape first — the inverse of France.',
          source: 'Regional practice' },
        { id: 'r-willamette', title: 'Willamette Valley', subtitle: 'USA · Pinot Noir',
          facts: [ { label: 'Country', value: 'USA (Oregon)' }, { label: 'Grape', value: 'Pinot Noir' }, { label: 'Climate', value: 'Cool, marginal' }, { label: 'Style', value: 'Burgundian — bright, red-fruited' } ],
          body: 'Cool, rainy Oregon turned out to be ideal for Pinot Noir, producing a more restrained, Burgundian style than California — bright red fruit, fresh acidity, earthy undertones.\n\nIt is the American reference for those who find Napa Cabernet too heavy.',
          source: 'Regional practice' },
        { id: 'r-mendoza', title: 'Mendoza', subtitle: 'Argentina · Malbec',
          facts: [ { label: 'Country', value: 'Argentina' }, { label: 'Grape', value: 'Malbec' }, { label: 'Altitude', value: 'High-altitude Andes foothills' }, { label: 'Style', value: 'Plush, dark-fruited, velvety' } ],
          body: 'Malbec, a minor Bordeaux blending grape, found its home in high-altitude Mendoza, where intense sunlight and cool nights give deeply coloured, velvety reds full of black plum and violet.\n\nAltitude (often 900–1,500 m) preserves acidity and freshness that the warmth would otherwise burn off.',
          source: 'Regional practice' },
        { id: 'r-barossa', title: 'Barossa Valley', subtitle: 'Australia · Shiraz',
          facts: [ { label: 'Country', value: 'Australia' }, { label: 'Grape', value: 'Shiraz (Syrah)' }, { label: 'Style', value: 'Rich, full, sweet-fruited, spicy' }, { label: 'Vines', value: 'Some of the world’s oldest' } ],
          body: 'The warm Barossa makes the archetypal Australian Shiraz — full-bodied, high in alcohol, with blackberry, licorice and a warm spice, often matured in American oak.\n\nIt holds some of the oldest continuously producing vines on earth (pre-phylloxera plantings from the 1800s), prized for their concentration.',
          source: 'Regional practice' },
        { id: 'r-marlborough', title: 'Marlborough', subtitle: 'New Zealand · Sauvignon Blanc',
          facts: [ { label: 'Country', value: 'New Zealand' }, { label: 'Grape', value: 'Sauvignon Blanc' }, { label: 'Style', value: 'Pungent, zesty, unmistakable' }, { label: 'Notes', value: 'Passionfruit, gooseberry, cut grass' } ],
          body: 'Marlborough put New Zealand on the map with a Sauvignon Blanc so distinctive it created its own style: explosively aromatic, zesty and green, with passionfruit and gooseberry over a herbal snap.\n\nThe cool, sunny climate and long ripening season concentrate those pungent aromatics.',
          source: 'Regional practice' },
        { id: 'r-stellenbosch', title: 'Stellenbosch', subtitle: 'South Africa · Cabernet & Chenin',
          facts: [ { label: 'Country', value: 'South Africa' }, { label: 'Reds', value: 'Cabernet Sauvignon, Syrah' }, { label: 'Whites', value: 'Chenin Blanc' }, { label: 'Unique', value: 'Pinotage (Pinot × Cinsault)' } ],
          body: 'Stellenbosch is South Africa’s red heartland — structured Cabernet and Syrah from mountain slopes — while Chenin Blanc (locally “Steen”) is the country’s versatile white workhorse.\n\nPinotage, a local crossing of Pinot Noir and Cinsault, is the signature grape: dark, smoky, and divisive.',
          source: 'Regional practice' },
        { id: 'r-loire', title: 'Loire Valley', subtitle: 'France · Chenin, Sauvignon, Cab Franc',
          facts: [ { label: 'Country', value: 'France' }, { label: 'Whites', value: 'Melon, Chenin, Sauvignon Blanc' }, { label: 'Reds', value: 'Cabernet Franc' }, { label: 'Span', value: 'Atlantic mouth → central France' } ],
          body: 'One river, four wine worlds. Muscadet at the Atlantic mouth (Melon de Bourgogne, sur lie — the oyster wine); Chenin Blanc mid-river in Vouvray and Anjou, running dry to sweet to sparkling; Cabernet Franc reds at Chinon and Bourgueil; Sauvignon Blanc at the eastern end in Sancerre and Pouilly-Fumé.\n\nCool climate throughout — the Loire is France’s garden of high-acid, food-loving wines.',
          source: 'Appellation practice' },
        { id: 'r-alsace', title: 'Alsace', subtitle: 'France · aromatic varietal whites',
          facts: [ { label: 'Country', value: 'France' }, { label: 'Grapes', value: 'Riesling, Gewurztraminer, Pinot Gris' }, { label: 'Rule-breaker', value: 'Labels by GRAPE' }, { label: 'Sweet', value: 'Vendanges Tardives' } ],
          body: 'Sheltered by the Vosges mountains, sunny Alsace is France’s exception: it labels by grape, Germanic bottles and all. The wines are aromatic and mostly DRY — taut Riesling, heady Gewurztraminer, rich Pinot Gris.\n\nVendanges Tardives (late harvest) and Sélection de Grains Nobles (botrytis) are the sweet exceptions, clearly marked.',
          source: 'Appellation regulation' },
        { id: 'r-provence', title: 'Provence', subtitle: 'France · the world’s rosé benchmark',
          facts: [ { label: 'Country', value: 'France' }, { label: 'Famous for', value: 'Pale, dry rosé' }, { label: 'Grapes', value: 'Grenache, Cinsault, Mourvèdre' }, { label: 'Also', value: 'Bandol reds (Mourvèdre)' } ],
          body: 'Provence made pale, bone-dry rosé a global category — Grenache and Cinsault pressed quickly for barely-there colour and plenty of freshness.\n\nThe serious red exception is Bandol: Mourvèdre on sea-facing terraces, dark and structured.',
          source: 'Appellation practice' },
        { id: 'r-veneto', title: 'Veneto', subtitle: 'Italy · Prosecco & Amarone',
          facts: [ { label: 'Country', value: 'Italy' }, { label: 'Sparkling', value: 'Prosecco (Glera, tank method)' }, { label: 'Red', value: 'Valpolicella → Amarone' }, { label: 'White', value: 'Soave (Garganega)' } ],
          body: 'The Veneto runs from Prosecco’s tank-method freshness to Amarone’s dried-grape power — the same Valpolicella grapes, raisined on mats (appassimento), fermented fully dry.\n\nSoave, from Garganega, is the underrated white: almondy, saline, age-worthy from the volcanic Classico hills.',
          source: 'DOC/DOCG regulation' },
        { id: 'r-sicily', title: 'Sicily & Etna', subtitle: 'Italy · Nero d’Avola & volcanic reds',
          facts: [ { label: 'Country', value: 'Italy' }, { label: 'Flagship', value: 'Nero d’Avola' }, { label: 'Rising star', value: 'Etna Rosso (Nerello Mascalese)' }, { label: 'Classic', value: 'Marsala (fortified)' } ],
          body: 'The Mediterranean’s biggest island ripens Nero d’Avola into dark, plummy reds — but the excitement is on the volcano: Nerello Mascalese on Etna’s high lava soils makes pale, taut reds often compared to Burgundy.\n\nMarsala, the west-coast fortified, is the island’s history lesson in a glass.',
          source: 'Regional practice' },
        { id: 'r-riasbaixas', title: 'Rías Baixas', subtitle: 'Spain · Albariño',
          facts: [ { label: 'Country', value: 'Spain (Galicia)' }, { label: 'Grape', value: 'Albariño' }, { label: 'Style', value: 'Peachy, saline, high acid' }, { label: 'Table', value: 'Born for shellfish' } ],
          body: 'Green, Atlantic Galicia is another Spain entirely: cool, wet, and white. Albariño from the drowned river valleys (rías) is peachy and saline, with the acidity of the nearby ocean.\n\nDrink it with the region’s own scallops and octopus — the pairing writes itself.',
          source: 'DO regulation' },
        { id: 'r-ribera', title: 'Ribera del Duero', subtitle: 'Spain · Tempranillo, turned up',
          facts: [ { label: 'Country', value: 'Spain' }, { label: 'Grape', value: 'Tempranillo (Tinto Fino)' }, { label: 'Altitude', value: '~800 m plateau' }, { label: 'Style', value: 'Darker, more powerful than Rioja' } ],
          body: 'The same grape as Rioja on a high, harsh plateau — scorching days, cold nights — gives something darker and more muscular. Vega Sicilia made the region’s legend; modern estates chase it.\n\nThink of Ribera as Rioja’s intense sibling: less vanilla, more black fruit and grip.',
          source: 'DO regulation' },
        { id: 'r-priorat', title: 'Priorat', subtitle: 'Spain · old vines on black slate',
          facts: [ { label: 'Country', value: 'Spain (Catalonia)' }, { label: 'Grapes', value: 'Garnacha, Cariñena' }, { label: 'Soil', value: 'Llicorella (black slate)' }, { label: 'Status', value: 'One of Spain’s two DOQ/DOCa' } ],
          body: 'Steep terraces of glinting black slate (llicorella) where old Garnacha and Cariñena vines yield almost nothing — and that scarcity concentrates everything. Revived in the 1980s by a handful of pioneers, now among Spain’s most prized reds.\n\nMineral, dense, warm — a wine that tastes like its rock.',
          source: 'DOQ regulation' },
        { id: 'r-jerez', title: 'Jerez — Sherry country', subtitle: 'Spain · flor, solera, and salt air',
          facts: [ { label: 'Country', value: 'Spain (Andalusia)' }, { label: 'Grape', value: 'Palomino (dry), PX (sweet)' }, { label: 'Magic', value: 'Flor yeast + solera ageing' }, { label: 'Styles', value: 'Fino → Amontillado → Oloroso' } ],
          body: 'The Sherry triangle — Jerez, Sanlúcar, El Puerto — fortifies AFTER fermentation, so the base is bone dry. Under a veil of flor yeast it stays pale and saline (Fino, Manzanilla); without flor it oxidises to walnut-dark Oloroso; Amontillado lives both lives in sequence.\n\nEverything moves through the solera, blending years into a continuous house style. The food wine the world keeps forgetting and sommeliers never do.',
          source: 'DO Jerez regulation' },
        { id: 'r-wachau', title: 'Wachau', subtitle: 'Austria · Grüner & Riesling on the Danube',
          facts: [ { label: 'Country', value: 'Austria' }, { label: 'Grapes', value: 'Grüner Veltliner, Riesling' }, { label: 'Style', value: 'Dry, precise, mineral' }, { label: 'Terrain', value: 'Stone terraces over the river' } ],
          body: 'A short, gorgeous stretch of the Danube where stone terraces hold Grüner Veltliner (white pepper, citrus) and taut dry Riesling.\n\nAustria’s wines are overwhelmingly dry — the Wachau at its best is as precise as fine Chablis, with its own peppery accent.',
          source: 'Regional practice' },
        { id: 'r-tokaj', title: 'Tokaj', subtitle: 'Hungary · the original noble-rot sweet wine',
          facts: [ { label: 'Country', value: 'Hungary' }, { label: 'Grape', value: 'Furmint' }, { label: 'Wine', value: 'Tokaji Aszú (botrytis)' }, { label: 'History', value: '“Wine of kings, king of wines”' } ],
          body: 'Centuries before Sauternes, Tokaj classified vineyards and bottled botrytis. Aszú berries — shrivelled by noble rot — are mashed into a Furmint base for sweet wines of electric acidity that age for generations.\n\nModern Tokaj also makes serious DRY Furmint: smoky, mineral, and finally getting its due.',
          source: 'Regional practice' },
        { id: 'r-sonoma', title: 'Sonoma', subtitle: 'USA · Napa’s cooler, quieter neighbour',
          facts: [ { label: 'Country', value: 'USA (California)' }, { label: 'Grapes', value: 'Chardonnay, Pinot Noir, Zinfandel' }, { label: 'Climate', value: 'Pacific fog through the gaps' }, { label: 'Feel', value: 'Farms, not châteaux' } ],
          body: 'Across the mountains from Napa, Sonoma opens to the Pacific: fog and cool air stream in, so Chardonnay and Pinot Noir lead — with old-vine Zinfandel in the warmer pockets.\n\nRussian River Valley Pinot and coastal Chardonnay are the calling cards; the mood is boots and barns rather than tasting-room marble.',
          source: 'Regional practice' },
        { id: 'r-coonawarra', title: 'Coonawarra', subtitle: 'Australia · Cabernet on terra rossa',
          facts: [ { label: 'Country', value: 'Australia' }, { label: 'Grape', value: 'Cabernet Sauvignon' }, { label: 'Soil', value: 'Terra rossa over limestone' }, { label: 'Marker', value: 'Eucalyptus-mint note' } ],
          body: 'A cigar-shaped strip of iron-red soil over pure limestone, cooled by Southern Ocean air — Australia’s classic Cabernet terroir, with a signature whiff of eucalyptus and mint.\n\nStructured, blackcurrant-driven, and long-lived: the Bordeaux argument, restated in an Australian accent.',
          source: 'Regional practice' },
        { id: 'r-margaret', title: 'Margaret River', subtitle: 'Australia · Cabernet & Chardonnay by the ocean',
          facts: [ { label: 'Country', value: 'Australia (WA)' }, { label: 'Reds', value: 'Cabernet Sauvignon (+Merlot)' }, { label: 'Whites', value: 'Chardonnay, Sauvignon–Sémillon' }, { label: 'Climate', value: 'Maritime, even, gentle' } ],
          body: 'Surrounded by ocean on three sides, Margaret River ripens slowly and evenly — Cabernet with fine-grained tannin and some of Australia’s most complete Chardonnay.\n\nIsolated, young (first vines 1967), and consistently excellent: the connoisseur’s corner of Australian wine.',
          source: 'Regional practice' },
        { id: 'r-otago', title: 'Central Otago', subtitle: 'New Zealand · Pinot at the edge of the world',
          facts: [ { label: 'Country', value: 'New Zealand' }, { label: 'Grape', value: 'Pinot Noir' }, { label: 'Claim', value: 'World’s southernmost fine-wine region' }, { label: 'Climate', value: 'Continental — NZ’s exception' } ],
          body: 'Inland, alpine, and continental where the rest of New Zealand is maritime: scorching days, frosty nights, thyme-covered hills. Pinot Noir here is darker and more muscular than Burgundy’s — sun-filled fruit with a wild-herb edge.\n\nThe world’s southernmost serious wine region, and its scenery’s only rival is the wine.',
          source: 'Regional practice' },
      ],
    },
    {
      id: 'grapes',
      title: 'Grapes to know',
      blurb: 'The dozen varieties that unlock most wine lists.',
      kind: 'list',
      entries: [
        { id: 'g-cabernet', title: 'Cabernet Sauvignon', subtitle: 'Red · full-bodied, high tannin',
          facts: [ { label: 'Home', value: 'Bordeaux (Left Bank)' }, { label: 'Also', value: 'Napa, Coonawarra, Tuscany' }, { label: 'Flavours', value: 'Cassis, cedar, green pepper' } ],
          body: 'The world’s most planted premium red — firm tannin, blackcurrant, and a savoury cedar/tobacco note with age. Thick skins give colour and structure; it blends famously with Merlot to soften.',
          source: 'Ampelography / regional practice' },
        { id: 'g-merlot', title: 'Merlot', subtitle: 'Red · plush, medium tannin',
          facts: [ { label: 'Home', value: 'Bordeaux (Right Bank)' }, { label: 'Flavours', value: 'Plum, black cherry, chocolate' } ],
          body: 'Softer and rounder than Cabernet, with plummy fruit and lower tannin — approachable young. It dominates the Right Bank (Pomerol, Saint-Émilion) and rescues countless blends from harshness.',
          source: 'Ampelography / regional practice' },
        { id: 'g-pinot', title: 'Pinot Noir', subtitle: 'Red · light, delicate, high acid',
          facts: [ { label: 'Home', value: 'Burgundy' }, { label: 'Also', value: 'Oregon, NZ, Germany (Spätburgunder)' }, { label: 'Flavours', value: 'Red cherry, raspberry, forest floor' } ],
          body: 'Thin-skinned and fussy to grow, Pinot Noir rewards effort with perfumed, translucent, silky reds. It is the great terroir transmitter — the reason Burgundy obsesses over single plots.',
          source: 'Ampelography / regional practice' },
        { id: 'g-chardonnay', title: 'Chardonnay', subtitle: 'White · the shape-shifter',
          facts: [ { label: 'Home', value: 'Burgundy' }, { label: 'Range', value: 'Steely (Chablis) → rich, oaked (Napa)' }, { label: 'In', value: 'Champagne (Blanc de Blancs)' } ],
          body: 'A near-neutral grape that reflects place and winemaking: unoaked and mineral in cool Chablis, buttery and tropical when warm-grown and oak-aged. Its malleability made it the world’s benchmark white.',
          source: 'Ampelography / regional practice' },
        { id: 'g-sangiovese', title: 'Sangiovese', subtitle: 'Red · savoury, high acid',
          facts: [ { label: 'Home', value: 'Tuscany' }, { label: 'Wines', value: 'Chianti, Brunello' }, { label: 'Flavours', value: 'Sour cherry, tomato leaf, herbs' } ],
          body: 'Italy’s most planted grape — bright acidity and grippy tannin that make it a natural at the table. Savoury and herbal rather than sweetly fruity, it is the backbone of Tuscan reds.',
          source: 'Ampelography / regional practice' },
        { id: 'g-nebbiolo', title: 'Nebbiolo', subtitle: 'Red · pale but powerful',
          facts: [ { label: 'Home', value: 'Piedmont' }, { label: 'Wines', value: 'Barolo, Barbaresco' }, { label: 'Flavours', value: 'Tar, roses, dried cherry' } ],
          body: 'A study in contradiction: pale garnet colour hiding ferocious tannin and acidity, with haunting tar-and-roses aromatics. Needs age (or decanting) to soften.',
          source: 'Ampelography / regional practice' },
        { id: 'g-syrah', title: 'Syrah / Shiraz', subtitle: 'Red · dark, peppery to jammy',
          facts: [ { label: 'Home', value: 'Northern Rhône' }, { label: 'As Shiraz', value: 'Australia (riper, sweeter)' }, { label: 'Flavours', value: 'Blackberry, black pepper, smoke' } ],
          body: 'Cool-climate Syrah (Rhône) is peppery and savoury; warm-climate Shiraz (Barossa) is plush and jammy. Same grape, two personalities set by climate — a clean lesson in how place shapes wine.',
          source: 'Ampelography / regional practice' },
        { id: 'g-grenache', title: 'Grenache', subtitle: 'Red · warm, sweet-fruited',
          facts: [ { label: 'Home', value: 'Southern Rhône, Spain (Garnacha)' }, { label: 'Role', value: 'The “G” in GSM blends' }, { label: 'Flavours', value: 'Strawberry, white pepper, herbs' } ],
          body: 'High in alcohol and sweet red fruit, low in colour and tannin — which is why it usually blends with structuring Syrah and Mourvèdre. The engine of Châteauneuf-du-Pape and Priorat.',
          source: 'Ampelography / regional practice' },
        { id: 'g-riesling', title: 'Riesling', subtitle: 'White · aromatic, high acid',
          facts: [ { label: 'Home', value: 'Germany, Alsace' }, { label: 'Range', value: 'Bone dry → lusciously sweet' }, { label: 'Flavours', value: 'Lime, green apple, petrol (aged)' } ],
          body: 'Arguably the finest white grape for transmitting place, with piercing acidity that balances any level of sweetness. Ages superbly, developing a distinctive kerosene note. Almost never oaked.',
          source: 'Ampelography / regional practice' },
        { id: 'g-sauvignon', title: 'Sauvignon Blanc', subtitle: 'White · zesty, herbaceous',
          facts: [ { label: 'Home', value: 'Loire (Sancerre), Bordeaux' }, { label: 'Also', value: 'Marlborough NZ' }, { label: 'Flavours', value: 'Gooseberry, grass, passionfruit' } ],
          body: 'High-acid and pungently aromatic, from flinty Sancerre to explosive Marlborough. Usually made fresh and unoaked; blended with Sémillon in Bordeaux, including sweet Sauternes.',
          source: 'Ampelography / regional practice' },
        { id: 'g-tempranillo', title: 'Tempranillo', subtitle: 'Red · savoury, medium everything',
          facts: [ { label: 'Home', value: 'Rioja, Ribera del Duero' }, { label: 'Flavours', value: 'Red plum, leather, dill (US oak)' } ],
          body: 'Spain’s noble red — moderate in acid, tannin and fruit, which makes it a canvas for oak ageing. Its savoury, leathery character deepens through the Crianza-to-Gran-Reserva ladder.',
          source: 'Ampelography / regional practice' },
        { id: 'g-malbec', title: 'Malbec', subtitle: 'Red · plush, dark, velvety',
          facts: [ { label: 'Home', value: 'Cahors (France), Mendoza (Argentina)' }, { label: 'Flavours', value: 'Black plum, violet, cocoa' } ],
          body: 'A minor Bordeaux grape reborn in high-altitude Argentina, where it makes deeply coloured, smooth, dark-fruited reds. Rustic and firm in its French home of Cahors; velvety in Mendoza.',
          source: 'Ampelography / regional practice' },
        { id: 'g-chenin', title: 'Chenin Blanc', subtitle: 'White · the acid chameleon',
          facts: [ { label: 'Home', value: 'Loire (Vouvray, Anjou)' }, { label: 'Also', value: 'South Africa (“Steen”)' }, { label: 'Range', value: 'Dry, sweet, sparkling — all of it' } ],
          body: 'Screaming acidity lets Chenin be anything: bone-dry, honeyed-sweet, or sparkling, often from the same hillside. Quince, apple, wet wool, honey with age. South Africa grows more of it than France does.',
          source: 'Ampelography / regional practice' },
        { id: 'g-viognier', title: 'Viognier', subtitle: 'White · perfume over power',
          facts: [ { label: 'Home', value: 'Condrieu (N. Rhône)' }, { label: 'Flavours', value: 'Apricot, honeysuckle, ginger' }, { label: 'Trick', value: 'Co-fermented with Syrah in Côte-Rôtie' } ],
          body: 'Headily aromatic and full-bodied with LOW acidity — the anti-Riesling. At its best in Condrieu; a splash co-fermented with Syrah stabilises colour and lifts aroma in Côte-Rôtie.',
          source: 'Ampelography / regional practice' },
        { id: 'g-gamay', title: 'Gamay', subtitle: 'Red · juicy, chillable',
          facts: [ { label: 'Home', value: 'Beaujolais' }, { label: 'Method', value: 'Carbonic maceration' }, { label: 'Serious side', value: 'The ten crus (Morgon, Fleurie…)' } ],
          body: 'Bright cherry and violet with soft tannin — often made by carbonic maceration (whole berries fermenting from within). Serve it lightly chilled. The crus prove it can age into something Pinot-like.',
          source: 'Ampelography / regional practice' },
        { id: 'g-gruner', title: 'Grüner Veltliner', subtitle: 'White · Austria’s pepper mill',
          facts: [ { label: 'Home', value: 'Austria (Wachau, Kamptal)' }, { label: 'Flavours', value: 'White pepper, citrus, lentil' }, { label: 'Style', value: 'Dry, precise' } ],
          body: 'Austria’s signature: crisp, dry whites with a telltale white-pepper bite. Everyday bottles are chuggable; single-vineyard Wachau versions age like fine Burgundy.',
          source: 'Ampelography / regional practice' },
        { id: 'g-albarino', title: 'Albariño', subtitle: 'White · the seafood white',
          facts: [ { label: 'Home', value: 'Rías Baixas (Galicia)' }, { label: 'Also', value: 'Portugal (Alvarinho, Vinho Verde)' }, { label: 'Flavours', value: 'Peach, citrus, sea spray' } ],
          body: 'Thick-skinned against Atlantic rain, giving stone fruit with saline freshness. Spain’s answer to the question “what goes with shellfish?” — and Portugal’s, as Alvarinho.',
          source: 'Ampelography / regional practice' },
        { id: 'g-zinfandel', title: 'Zinfandel / Primitivo', subtitle: 'Red · one grape, two lives',
          facts: [ { label: 'Homes', value: 'California · Puglia' }, { label: 'DNA', value: 'Same Croatian-born variety' }, { label: 'Flavours', value: 'Blackberry jam, pepper, warmth' } ],
          body: 'DNA testing ended the argument: California’s Zinfandel and Puglia’s Primitivo are the same grape. Big, jammy, high-alcohol reds — old-vine Californian bottlings are the serious face.',
          source: 'Ampelography (DNA-established)' },
      ],
    },
  ],
};
