import type { DomainContent } from '../knowledge-core/types';

// Wine v0 — Block 1 (systematic tasting + pairing logic), the country-labelling insight,
// and classic appellation facts. All items are stable, factual, and public (appellation
// regulations / grape composition). source + verified per the accuracy gate; Simon should
// still spot-check specifics per spec 02 §3 before relying on them.
export const WINE: DomainContent = {
  id: 'wine',
  title: 'Wine',
  blurb: 'Tasting · regions · grapes',
  accent: '#7b2f3f',
  newPerDay: 6,
  cards: [
    // --- Block 1: systematic tasting + pairing logic ---
    { id: 'w-taste-axes', type: 'why', prompt: 'Systematic tasting fixes the things you assess in every glass. What are they?',
      explanation: 'Acid, tannin, alcohol, body, fruit, finish — a fixed structure so every bottle becomes a comparable data point rather than an anecdote.',
      source: 'Spec 03 §Wine, block 1', verified: true, tag: 'tasting' },
    { id: 'w-taste-first', type: 'why', prompt: 'Why taste to a fixed structure from the very first bottle?',
      explanation: 'Without a structure, each subsequent bottle is an isolated impression. With one, you build a mental library you can compare across regions and vintages.',
      source: 'Spec 03 §Wine', verified: true, tag: 'tasting' },
    { id: 'w-pair-acid', type: 'cloze', prompt: 'Pairing logic: match acidity to ___ (rich, fatty dishes).',
      answer: 'fat', accept: ['fat', 'fatty', 'richness'], explanation: 'Acid cuts through fat and refreshes the palate — think a crisp white with fried food.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing' },
    { id: 'w-pair-tannin', type: 'cloze', prompt: 'Pairing logic: match tannin to ___ (it binds and softens against it).',
      answer: 'protein', accept: ['protein', 'proteins'], explanation: 'Tannin binds with protein and fat, so a tannic red feels smoother with a steak than on its own.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing' },
    { id: 'w-pair-sweet', type: 'cloze', prompt: 'Pairing a dessert: the wine’s sweetness should sit ___ the dish’s sweetness.',
      answer: 'above', accept: ['above', 'higher'], explanation: 'A wine less sweet than the dessert tastes thin and sour beside it — sweet wine must out-sweet the plate.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing' },
    { id: 'w-pair-weight', type: 'cloze', prompt: 'Pairing logic: match the ___ of the wine to the weight of the dish.',
      answer: 'weight', accept: ['weight', 'body'], explanation: 'A light dish is flattened by a heavy wine and vice versa — weight to weight, body to body.',
      source: 'Spec 03 §Wine, pairing', verified: true, tag: 'pairing' },

    // --- The structural insight the module is built on ---
    { id: 'w-label-fr-nw', type: 'why', prompt: 'Each wine country answers “what does the label tell you?” differently. What are France’s and the New World’s answers?',
      explanation: 'France labels by PLACE (appellation) — the grape is usually absent. The New World labels by GRAPE first, region second. Learning that difference is worth more than any single appellation.',
      source: 'Spec 03 §Wine, organising principle', verified: true, tag: 'labelling' },
    { id: 'w-burgundy-exception', type: 'why', prompt: 'Burgundy is France’s exception to place-labelling. How?',
      explanation: 'It is monovarietal — Pinot Noir for reds, Chardonnay for whites — yet still labelled by PLACE, not grape. The rule (label by place) holds; the blending norm does not.',
      source: 'Spec 03 §Wine, France', verified: true, tag: 'France' },

    // --- Classic appellation / grape facts ---
    { id: 'w-brunello', type: 'instance', prompt: 'Brunello di Montalcino is made from 100% which grape?',
      answer: 'Sangiovese', accept: ['sangiovese'], explanation: 'Brunello is 100% Sangiovese from the warmer, drier Montalcino mesoclimate, with long ageing (min. five years).',
      source: 'DOCG regulations', verified: true, tag: 'Italy' },
    { id: 'w-barolo', type: 'instance', prompt: 'Barolo and Barbaresco are made from 100% which grape?',
      answer: 'Nebbiolo', accept: ['nebbiolo'], explanation: 'Both Piedmont DOCGs are 100% Nebbiolo — high acid, high tannin, pale colour that belies its power.',
      source: 'DOCG regulations', verified: true, tag: 'Italy' },
    { id: 'w-chianti', type: 'cloze', prompt: 'Chianti Classico must be at least ___% Sangiovese.',
      answer: '80', accept: ['80', '80%'], explanation: 'Chianti Classico requires a minimum 80% Sangiovese, with the rest from permitted local or international grapes.',
      source: 'DOCG regulations', verified: true, tag: 'Italy' },
    { id: 'w-gsm', type: 'instance', prompt: 'The southern Rhône “GSM” blend is Grenache, Syrah, and ___.',
      answer: 'Mourvèdre', accept: ['mourvedre', 'mourvèdre'], explanation: 'Grenache (fruit/warmth), Syrah (structure/spice), Mourvèdre (savoury grip) — the backbone of Châteauneuf-du-Pape and much of the south.',
      source: 'Appellation practice', verified: true, tag: 'France' },
    { id: 'w-bordeaux', type: 'why', prompt: 'Name the principal red grapes permitted in a classic Bordeaux blend.',
      explanation: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, and Malbec. Bordeaux blends rather than relying on one grape — the mix hedges vintage and site.',
      source: 'Appellation practice', verified: true, tag: 'France' },
    { id: 'w-rioja-ladder', type: 'cloze', prompt: 'Spain’s ageing ladder: Joven → Crianza → Reserva → ___.',
      answer: 'Gran Reserva', accept: ['gran reserva', 'granreserva'], explanation: 'Each step requires more time in oak and bottle before release.',
      source: 'Spanish DO ageing rules', verified: true, tag: 'Spain' },
    { id: 'w-rioja-meaning', type: 'why', prompt: 'In Spain, what do Crianza / Reserva / Gran Reserva classify — and what is it commonly misread as?',
      explanation: 'They classify TIME IN OAK AND BOTTLE (ageing), not the region or inherent quality. It is widely misread as a quality or origin tier — it is an ageing scale.',
      source: 'Spec 03 §Wine, Spain', verified: true, tag: 'Spain' },
    { id: 'w-pradikat', type: 'cloze', prompt: 'Germany’s Prädikat ripeness ladder: Kabinett → Spätlese → Auslese → BA → ___.',
      answer: 'TBA', accept: ['tba', 'trockenbeerenauslese'], explanation: 'Trockenbeerenauslese (TBA) — from individually selected botrytised, shrivelled berries.',
      source: 'German wine law', verified: true, tag: 'Germany' },
    { id: 'w-pradikat-meaning', type: 'why', prompt: 'German Prädikat levels (Kabinett…TBA) measure what, exactly?',
      explanation: 'Must weight — the sugar/ripeness of the grapes AT HARVEST — not the sweetness of the finished wine. A Kabinett can be made bone dry.',
      source: 'Spec 03 §Wine, Germany', verified: true, tag: 'Germany' },
    { id: 'w-champagne', type: 'instance', prompt: 'Champagne’s three principal grapes are Chardonnay, Pinot Noir, and ___.',
      answer: 'Meunier', accept: ['meunier', 'pinot meunier'], explanation: 'Meunier adds fruit and approachability; Chardonnay finesse; Pinot Noir structure.',
      source: 'Appellation practice', verified: true, tag: 'Champagne' },
  ],
};
