// Bakes Natural Earth country outlines (public domain, via world-atlas) into a
// static TS module. Coordinate space: equirectangular 360x180 — x = lon+180,
// y = 90−lat — matching the MapPin convention. Run: node scripts/build-maps.mjs
import { readFileSync, writeFileSync } from 'fs';
import { createRequire } from 'module';
import * as topojson from 'topojson-client';
const require = createRequire(import.meta.url);

const topo = JSON.parse(readFileSync(require.resolve('world-atlas/countries-110m.json'), 'utf8'));
const fc = topojson.feature(topo, topo.objects.countries);

const px = (lon) => (lon + 180).toFixed(1);
const py = (lat) => (90 - lat).toFixed(1);
// Rings crossing the antimeridian (Russia, Fiji…) would draw a horizontal streak
// across the map. Fix: shift negative-lon points +360 — they run off the right
// edge and the SVG viewBox clips them cleanly.
const ring = (pts) => {
  let crosses = false;
  for (let i = 1; i < pts.length; i++) if (Math.abs(pts[i][0] - pts[i - 1][0]) > 180) { crosses = true; break; }
  const fixed = crosses ? pts.map(([lon, lat]) => [lon < 0 ? lon + 360 : lon, lat]) : pts;
  return 'M' + fixed.map(([lon, lat]) => `${px(lon)} ${py(lat)}`).join('L') + 'Z';
};

const out = [];
for (const f of fc.features) {
  if (!f.geometry) continue;
  const name = (f.properties && f.properties.name) || '';
  let d = '';
  if (f.geometry.type === 'Polygon') d = f.geometry.coordinates.map(ring).join('');
  else if (f.geometry.type === 'MultiPolygon') d = f.geometry.coordinates.map((poly) => poly.map(ring).join('')).join('');
  if (d) out.push({ name, d });
}

const ts = `// GENERATED by scripts/build-maps.mjs — Natural Earth 110m via world-atlas (public domain).
// Equirectangular 360x180: x = lon+180, y = 90−lat. Do not edit by hand.
export interface CountryPath { name: string; d: string }
export const COUNTRY_PATHS: CountryPath[] = ${JSON.stringify(out)};
`;
writeFileSync('/Users/simonfelixwalenski/Desktop/DailyLearning/src/modules/knowledge-core/mapdata.ts', ts);
console.log('countries:', out.length, '| bytes:', ts.length);
