import type { DomainContent } from '../knowledge-core/types';

// Art — recognition first (Simon's brief, 2026-07-25): see a picture → know the painter,
// ideally the title and rough year, and have one thing worth saying. Conversational, not
// exam-level. Structured like chess chapters: each unit = a movement (context lessons +
// its painters); the review drills image → artist. All images are Met Open Access CC0,
// downloaded at authoring time and committed under public/art (offline gate). Titles,
// artists and dates come straight from the Met's own metadata.
export const ART: DomainContent = {
  id: 'art',
  title: 'Art',
  blurb: 'See it · name it · say something true',
  accent: '#b07d2c',
  newPerDay: 6,
  goal: {
    title: 'Goal — Conversational art',
    blurb: 'Seven units, each a movement with its painters. The aim: shown a picture, you know who painted it, roughly when, and one thing worth saying. Recognition first — no exam.',
  },
  blocks: [
    {
      id: 'looking',
      title: 'Ways of looking',
      primer: 'Before any names, learn to look. These are the tools you use on every single work — the layer that turns recognising a painting into having something to say about it.',
      lessons: [
        { id: 'composition', title: 'Composition & line', body: 'Composition is how the artist arranges everything to lead your eye — balance, a focal point, the path your gaze travels. Notice where you look first, and what pulls you there.\n\nLine does two jobs: contour (the edges of things) and gesture (energy and movement). A diagonal feels active; a horizontal, calm. Much of a picture’s feeling is decided before you notice any subject.' },
        { id: 'colour-light', title: 'Colour, light, space', body: 'Colour carries temperature (warm advances, cool recedes) and relationships (complementaries intensify each other). Light models form: chiaroscuro is strong light-to-dark contrast for drama and volume.\n\nSpace is built by perspective — linear (converging lines) or atmospheric (distant things paler and bluer). And facture — visible brushwork — is itself expressive: smooth and hidden, or thick and gestural.' },
        { id: 'the-question', title: 'The one question', body: 'For every work, ask: what problem was this artist solving?\n\nThat single question is the difference between naming a painting and understanding it. Knowing Van Gogh painted a wheat field is a fact; seeing that he was making paint itself carry emotion is the thing worth saying at dinner.' },
      ],
    },
    {
      id: 'renaissance',
      title: 'The Northern Renaissance',
      primer: 'While Italy perfected idealised bodies, the North perfected LOOKING: the new oil medium let Flemish and German painters render the world in astonishing detail — and made everyday life a worthy subject.',
      lessons: [
        { id: 'ren-north', title: 'Oil, detail, daily life', body: 'Oil paint dries slowly and layers thinly, so Northern painters could build detail no fresco could hold — individual hairs, reflections in glass, fifty villagers each doing something specific.\n\nPieter Bruegel the Elder turned that eye onto peasant life and the turning seasons, painted from a high, sweeping vantage — ordinary labour given the scale once reserved for saints.\n\nAlbrecht Dürer carried Renaissance ideas across the Alps and, through the printing press, across Europe: his engravings and woodcuts made him the first artist famous by reproduction.' },
      ],
    },
    {
      id: 'baroque',
      title: 'Baroque drama & the Spanish court',
      primer: 'Around 1600, painting learned theatre: raking light out of darkness, saints with dirty feet, real faces caught mid-gesture. The style spread from Rome to the courts of Spain.',
      lessons: [
        { id: 'bar-caravaggio', title: 'Caravaggio’s spotlight', body: 'Caravaggio lit sacred scenes like crime scenes — figures surfacing from near-black (tenebrism), models recruited off the street. The shock was immediacy: the Denial of Saint Peter happens NOW, to people you might know.\n\nHalf of Europe painted in his wake; the dramatic light you recognise in Rembrandt descends from this.' },
        { id: 'bar-spain', title: 'Spain: El Greco & Velázquez', body: 'El Greco — Greek-born, Venice-trained, Toledo-based — stretched figures into flame-like verticals lit by inner ecstasy. Nobody painted like him for three centuries, until the moderns claimed him as an ancestor.\n\nVelázquez, court painter to Philip IV, was the painter’s painter: air and light around real people, brushwork that dissolves up close and snaps into focus at distance. Manet later called him “the painter of painters.”' },
      ],
    },
    {
      id: 'dutch',
      title: 'The Dutch Golden Age',
      primer: 'Your flagship unit — the Najdorf of this course. A 17th-century merchant republic with no church or king to please bought portraits, taverns and quiet rooms — and three painters made those subjects immortal.',
      lessons: [
        { id: 'dutch-era', title: 'A republic of pictures', body: 'The 1600s Netherlands was Protestant, rich and bourgeois: no altarpieces, no royal mythology. Art became a market good — merchants bought scenes of themselves, their cities, their tables.\n\nThat market created specialists: portraits, still lifes, seascapes, church interiors — and an eye for light on ordinary things that no culture had prized before.' },
        { id: 'dutch-three', title: 'Rembrandt, Vermeer, Hals', body: 'Rembrandt used Caravaggio’s light for psychology instead of drama: faces emerge from shadow carrying a whole inner life. Watch his self-portraits age with him.\n\nVermeer made stillness the subject — a maid asleep, a letter read by window light, time stopped in a Delft room. Only ~35 paintings survive, which is part of the legend.\n\nFrans Hals painted the laugh itself: loose, fast strokes that catch people mid-toast — brushwork the Impressionists would rediscover two centuries later.' },
      ],
    },
    {
      id: 'romantics',
      title: 'Revolution, Romantics & Realists',
      primer: 'From the French Revolution to the 1860s, painting argued about what it was FOR: stoic virtue (David), witness (Goya), the sublime (Friedrich, Turner), national myth (Leutze) — until Courbet said: just paint what is.',
      lessons: [
        { id: 'rom-neo', title: 'Neoclassicism: David', body: 'Jacques-Louis David stripped painting to moral theatre — sculptural figures, shallow stage space, Roman virtue. The Death of Socrates (1787) is a manifesto: reason, calm, principle unto death, painted on the eve of the Revolution he would join.' },
        { id: 'rom-sublime', title: 'Goya, Friedrich, Turner', body: 'Goya began as a court portraitist and ended painting nightmares — war, folly, black paintings. He is the bridge from courtly polish to modern unease.\n\nCaspar David Friedrich put small figures with their backs to us (the Rückenfigur) before moons and mountains — you stand IN the painting, feeling the immensity. Turner went further: light and weather dissolving form itself, decades before Impressionism.\n\nAnd in America, Leutze’s Washington Crossing the Delaware shows what Romantic machinery does for national myth — historically loose, emotionally exact.' },
        { id: 'rom-realism', title: 'Courbet’s refusal', body: '“Show me an angel and I’ll paint one.” Gustave Courbet rejected both stoic Rome and Romantic storms: ordinary people and plain places at heroic scale, painted thick.\n\nRealism is the hinge — once subject matter was freed, the Impressionists only had to free the brushwork.' },
      ],
    },
    {
      id: 'impressionists',
      title: 'Impressionism & its sparks',
      primer: 'The 1860s–80s revolution: leave the studio, catch the moment, let the stroke show. Its sparks came from two directions — Manet’s scandals and Japanese prints.',
      lessons: [
        { id: 'imp-sparks', title: 'Manet & the Japanese print', body: 'Édouard Manet never called himself an Impressionist, but his flat light, modern subjects and Salon scandals (Olympia, 1863) opened the door the younger painters walked through.\n\nThe other spark came in the mail: Japanese ukiyo-e woodblocks — Hokusai’s Great Wave above all — with their cropped compositions, flat colour and everyday subjects. “Japonisme” taught Degas his tilted floors and cut-off dancers.' },
        { id: 'imp-circle', title: 'The circle', body: 'Renoir painted pleasure — dappled light on skin, café afternoons, By the Seashore’s soft air. Degas insisted he was a draughtsman: ballet classes, laundresses, bathers, seen at odd angles as if through a doorway.\n\nSeurat, a generation younger, tried to make the Impression scientific — building light from dots of pure colour (pointillism). His early Mower already shows the calm, constructed stillness.' },
        { id: 'imp-americans', title: 'The American cousins', body: 'Winslow Homer painted the American fact — a Civil War veteran mowing a field in 1865 reads as elegy without a single soldier shown.\n\nJohn Singer Sargent painted transatlantic society with Velázquez’s bravura; Madame X (1884) was such a scandal at the Salon — that strap, that pallor — that he left Paris for London.' },
      ],
    },
    {
      id: 'moderns',
      title: 'Toward modern art',
      primer: 'After Impressionism, three roads: structure (Cézanne), feeling (Van Gogh), symbol (Gauguin, Klimt, Hodler) — plus one self-taught customs officer the modernists adored. Follow these and you can explain where Picasso came from.',
      lessons: [
        { id: 'mod-post', title: 'Cézanne, Van Gogh, Gauguin', body: 'Cézanne wanted to make Impressionism “solid and durable” — building card players and fruit from firm planes of colour. Cubism starts here.\n\nVan Gogh made the stroke itself emotional: wheat, cypress and cloud all writhing with the same thick energy. Ten years of work, one sale, then the twentieth century caught up.\n\nGauguin left for Brittany and Tahiti chasing colour freed from description — flat, symbolic, dreamlike. Even his still lifes glow with it.' },
        { id: 'mod-symbol', title: 'Symbolists & a customs officer', body: 'Klimt led Vienna’s Secession toward ornament and gold; even his early society portraits shimmer with surface. Hodler arranged rhythmic, dreaming figures he called “parallelism.”\n\nAnd Henri Rousseau — “Le Douanier,” a toll collector who never trained — painted jungles he had only seen in greenhouses. The avant-garde laughed, then Picasso threw him a banquet. Sincerity outlived technique.' },
      ],
    },
  ],
  cards: [
    // --- Ways of looking (concepts) ---
    { id: 'a-composition', type: 'why', prompt: 'In formal analysis, what does “composition” govern?',
      explanation: 'How the artist leads your eye — balance, focal point, and the path your gaze travels. Much of a picture’s feeling is set by arrangement before you register the subject.',
      source: 'Formal analysis', verified: true, tag: 'looking', unit: 'looking' },
    { id: 'a-chiaroscuro', type: 'cloze', prompt: 'Strong contrast of light and dark for drama and volume is called ___.',
      answer: 'chiaroscuro', accept: ['chiaroscuro'], explanation: 'From Italian “light-dark”. Caravaggio made it theatre; Rembrandt made it psychology.',
      source: 'Formal analysis', verified: true, tag: 'looking', unit: 'looking' },
    { id: 'a-question', type: 'why', prompt: 'The single question to ask of every artwork?',
      explanation: '“What problem was this artist solving?” It converts recognition into understanding — and into conversation.',
      source: 'Formal analysis', verified: true, tag: 'looking', unit: 'looking' },

    // --- Northern Renaissance ---
    { id: 'a-bruegel', type: 'instance', image: 'art/435809.jpg', prompt: 'Who painted this?',
      answer: 'Bruegel', accept: ['bruegel', 'brueghel', 'pieter bruegel', 'pieter bruegel the elder'],
      explanation: 'Pieter Bruegel the Elder, “The Harvesters” (1565). Northern Renaissance — peasant labour and the seasons given grand scale, from a high sweeping vantage.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'N. Renaissance', unit: 'renaissance' },
    { id: 'a-durer', type: 'instance', image: 'art/436243.jpg', prompt: 'Who painted this?',
      answer: 'Dürer', accept: ['durer', 'dürer', 'albrecht durer', 'albrecht dürer'],
      explanation: 'Albrecht Dürer, “Salvator Mundi” (ca. 1505). The German master who carried the Renaissance north — and became Europe-famous through his prints.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'N. Renaissance', unit: 'renaissance' },

    // --- Baroque & Spain ---
    { id: 'a-caravaggio', type: 'instance', image: 'art/437986.jpg', prompt: 'Who painted this?',
      answer: 'Caravaggio', accept: ['caravaggio'],
      explanation: 'Caravaggio, “The Denial of Saint Peter” (1610). Baroque tenebrism — sacred drama lit like a crime scene, painted in his final year.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Baroque', unit: 'baroque' },
    { id: 'a-elgreco', type: 'instance', image: 'art/436572.jpg', prompt: 'Who painted this?',
      answer: 'El Greco', accept: ['el greco', 'greco'],
      explanation: 'El Greco, “Christ Healing the Blind” (ca. 1570). Elongated, flame-lit figures nobody matched for three centuries — the moderns’ favourite ancestor.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Spain', unit: 'baroque' },
    { id: 'a-velazquez', type: 'instance', image: 'art/437871.jpg', prompt: 'Who painted this?',
      answer: 'Velázquez', accept: ['velazquez', 'velásquez', 'velázquez', 'diego velazquez'],
      explanation: 'Velázquez, “The Supper at Emmaus” (1622–23). Spain’s court painter — “the painter of painters” (Manet); loose strokes that snap into focus at distance.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Spain', unit: 'baroque' },

    // --- Dutch Golden Age ---
    { id: 'a-rembrandt', type: 'instance', image: 'art/437398.jpg', prompt: 'Who painted this?',
      answer: 'Rembrandt', accept: ['rembrandt', 'rembrandt van rijn'],
      explanation: 'Rembrandt, “Flora” (ca. 1654). Dutch Golden Age — chiaroscuro turned inward, for psychology rather than theatre.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Dutch Golden Age', unit: 'dutch' },
    { id: 'a-vermeer', type: 'instance', image: 'art/437878.jpg', prompt: 'Who painted this?',
      answer: 'Vermeer', accept: ['vermeer', 'johannes vermeer'],
      explanation: 'Vermeer, “A Maid Asleep” (ca. 1656–57). Window light, absolute stillness, a Delft room where time has stopped — one of only ~35 surviving Vermeers.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Dutch Golden Age', unit: 'dutch' },
    { id: 'a-hals', type: 'instance', image: 'art/436616.jpg', prompt: 'Who painted this?',
      answer: 'Hals', accept: ['hals', 'frans hals'],
      explanation: 'Frans Hals, “Young Man and Woman in an Inn” (1623). The laugh caught live — loose, fast strokes the Impressionists would rediscover.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Dutch Golden Age', unit: 'dutch' },

    // --- Revolution, Romantics & Realists ---
    { id: 'a-david', type: 'instance', image: 'art/436105.jpg', prompt: 'Who painted this?',
      answer: 'David', accept: ['david', 'jacques louis david', 'jacques-louis david'],
      explanation: 'Jacques-Louis David, “The Death of Socrates” (1787). Neoclassicism — reason and virtue as moral theatre, on the eve of the Revolution.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Neoclassicism', unit: 'romantics' },
    { id: 'a-goya', type: 'instance', image: 'art/436543.jpg', prompt: 'Who painted this?',
      answer: 'Goya', accept: ['goya', 'francisco goya', 'francisco de goya'],
      explanation: 'Goya, “Josefa de Castilla Portugal” (1804). The Spanish court portraitist who would end in nightmares — the bridge from polish to modern unease.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Romanticism', unit: 'romantics' },
    { id: 'a-friedrich', type: 'instance', image: 'art/438417.jpg', prompt: 'Who painted this?',
      answer: 'Friedrich', accept: ['friedrich', 'caspar david friedrich'],
      explanation: 'Caspar David Friedrich, “Two Men Contemplating the Moon” (ca. 1825–30). German Romanticism — his signature Rückenfigur: backs to us, so we stand inside the awe.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Romanticism', unit: 'romantics' },
    { id: 'a-turner', type: 'instance', image: 'art/383001.jpg', prompt: 'Who made this?',
      answer: 'Turner', accept: ['turner', 'jmw turner', 'j.m.w. turner', 'william turner'],
      explanation: 'J.M.W. Turner, from the “Liber Studiorum” (1811). Romanticism — light and atmosphere already dissolving solid form, decades early.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Romanticism', unit: 'romantics' },
    { id: 'a-turner2', type: 'instance', image: 'art/437853.jpg', prompt: 'Same hand, different work — who painted this?',
      answer: 'Turner', accept: ['turner', 'jmw turner', 'j.m.w. turner', 'william turner'],
      explanation: 'Turner again — “Venice, from the Porch of Madonna della Salute” (ca. 1835). Recognising the HAND across works is the real skill.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Romanticism', unit: 'romantics' },
    { id: 'a-leutze', type: 'instance', image: 'art/11417.jpg', prompt: 'Who painted this?',
      answer: 'Leutze', accept: ['leutze', 'emanuel leutze'],
      explanation: 'Emanuel Leutze, “Washington Crossing the Delaware” (1851). Romantic history painting — historically loose, emotionally exact national myth.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'History painting', unit: 'romantics' },
    { id: 'a-courbet', type: 'instance', image: 'art/436023.jpg', prompt: 'Who painted this?',
      answer: 'Courbet', accept: ['courbet', 'gustave courbet'],
      explanation: 'Gustave Courbet, “The Source of the Loue” (1864). Realism — “show me an angel and I’ll paint one”; plain places painted thick, at heroic scale.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Realism', unit: 'romantics' },

    // --- Impressionism & its sparks ---
    { id: 'a-hokusai', type: 'instance', image: 'art/45434.jpg', prompt: 'Who made this?',
      answer: 'Hokusai', accept: ['hokusai', 'katsushika hokusai'],
      explanation: 'Hokusai, “The Great Wave off Kanagawa” (ca. 1830–32). Ukiyo-e woodblock — the cropped, flat drama that taught the Impressionists to see differently.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Ukiyo-e', unit: 'impressionists' },
    { id: 'a-manet', type: 'instance', image: 'art/438002.jpg', prompt: 'Who painted this?',
      answer: 'Manet', accept: ['manet', 'edouard manet', 'édouard manet'],
      explanation: 'Édouard Manet, “Madame Manet at Bellevue” (1880). The Salon scandal-maker who opened the door Impressionism walked through.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Impressionism', unit: 'impressionists' },
    { id: 'a-renoir', type: 'instance', image: 'art/437430.jpg', prompt: 'Who painted this?',
      answer: 'Renoir', accept: ['renoir', 'auguste renoir', 'pierre-auguste renoir'],
      explanation: 'Renoir, “By the Seashore” (1883). Impressionism at its most pleasurable — soft air, dappled light, painted happiness.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Impressionism', unit: 'impressionists' },
    { id: 'a-degas', type: 'instance', image: 'art/436135.jpg', prompt: 'Who made this?',
      answer: 'Degas', accept: ['degas', 'edgar degas'],
      explanation: 'Degas, “Dancer with a Fan” (ca. 1880). Impressionism — cropped, off-centre framing learned from photography and Japanese prints.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Impressionism', unit: 'impressionists' },
    { id: 'a-degas2', type: 'instance', image: 'art/436121.jpg', prompt: 'Same hand, different work — who painted this?',
      answer: 'Degas', accept: ['degas', 'edgar degas'],
      explanation: 'Degas again — “A Woman Seated beside a Vase of Flowers” (1865). The sitter pushed off-centre, the flowers centre stage: his tilt, already there.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Impressionism', unit: 'impressionists' },
    { id: 'a-seurat', type: 'instance', image: 'art/459116.jpg', prompt: 'Who painted this?',
      answer: 'Seurat', accept: ['seurat', 'georges seurat'],
      explanation: 'Georges Seurat, “The Mower” (1881–82). The future inventor of pointillism — the constructed calm is already visible.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Impressionism', unit: 'impressionists' },
    { id: 'a-homer', type: 'instance', image: 'art/11145.jpg', prompt: 'Who painted this?',
      answer: 'Homer', accept: ['homer', 'winslow homer'],
      explanation: 'Winslow Homer, “The Veteran in a New Field” (1865). American realism — a Civil War elegy without a single soldier shown.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'American', unit: 'impressionists' },
    { id: 'a-sargent', type: 'instance', image: 'art/12127.jpg', prompt: 'Who painted this?',
      answer: 'Sargent', accept: ['sargent', 'john singer sargent'],
      explanation: 'John Singer Sargent, “Madame X” (1883–84). The Salon scandal — that strap, that pallor — that drove him from Paris to London.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'American', unit: 'impressionists' },

    // --- Toward modern art ---
    { id: 'a-cezanne', type: 'instance', image: 'art/435868.jpg', prompt: 'Who painted this?',
      answer: 'Cézanne', accept: ['cezanne', 'cézanne', 'paul cezanne', 'paul cézanne'],
      explanation: 'Cézanne, “The Card Players” (1890–92). Post-Impressionism — solidity rebuilt from planes of colour; the road to Cubism.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Post-Impressionism', unit: 'moderns' },
    { id: 'a-vangogh', type: 'instance', image: 'art/436535.jpg', prompt: 'Who painted this?',
      answer: 'Van Gogh', accept: ['van gogh', 'vincent van gogh', 'gogh'],
      explanation: 'Van Gogh, “Wheat Field with Cypresses” (1889). Post-Impressionism — the stroke itself carries the feeling.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Post-Impressionism', unit: 'moderns' },
    { id: 'a-vangogh2', type: 'instance', image: 'art/459123.jpg', prompt: 'Same hand, different work — who painted this?',
      answer: 'Van Gogh', accept: ['van gogh', 'vincent van gogh', 'gogh'],
      explanation: 'Van Gogh again — “Madame Roulin and Her Baby” (1888). The Arles palette and urgent stroke, in a portrait.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Post-Impressionism', unit: 'moderns' },
    { id: 'a-gauguin', type: 'instance', image: 'art/437999.jpg', prompt: 'Who painted this?',
      answer: 'Gauguin', accept: ['gauguin', 'paul gauguin'],
      explanation: 'Paul Gauguin, “Still Life with Teapot and Fruit” (1896, Tahiti). Colour freed from description — flat, symbolic, glowing.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Post-Impressionism', unit: 'moderns' },
    { id: 'a-klimt', type: 'instance', image: 'art/436820.jpg', prompt: 'Who painted this?',
      answer: 'Klimt', accept: ['klimt', 'gustav klimt'],
      explanation: 'Gustav Klimt, “Serena Pulitzer Lederer” (1899). Vienna Secession — the society portraitist on his way to the gold.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Symbolism', unit: 'moderns' },
    { id: 'a-hodler', type: 'instance', image: 'art/634108.jpg', prompt: 'Who painted this?',
      answer: 'Hodler', accept: ['hodler', 'ferdinand hodler'],
      explanation: 'Ferdinand Hodler, “The Dream of the Shepherd” (1896). Symbolism — rhythmic, dreaming figures; meaning carried by pattern, not realism.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Symbolism', unit: 'moderns' },
    { id: 'a-rousseau', type: 'instance', image: 'art/438822.jpg', prompt: 'Who painted this?',
      answer: 'Rousseau', accept: ['rousseau', 'henri rousseau', 'le douanier'],
      explanation: 'Henri Rousseau, “The Repast of the Lion” (ca. 1907). The self-taught “Douanier” — jungles from greenhouse visits; Picasso threw him a banquet.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Naïve', unit: 'moderns' },
  ],

  explore: [
    {
      id: 'ex-dutch',
      title: 'The Dutch Golden Age',
      blurb: 'A merchant republic bought pictures of itself — and got Rembrandt, Vermeer and Hals.',
      kind: 'gallery',
      entries: [
        { id: 'e-rembrandt', title: 'Flora', subtitle: 'Rembrandt · ca. 1654', image: 'art/437398.jpg',
          facts: [ { label: 'Movement', value: 'Dutch Golden Age' }, { label: 'Year', value: 'ca. 1654' } ],
          body: 'Chiaroscuro turned inward: the figure emerges from darkness as if from thought. Rembrandt’s lifelong problem — making paint carry a human interior.', source: 'Met Open Access (CC0)' },
        { id: 'e-vermeer', title: 'A Maid Asleep', subtitle: 'Johannes Vermeer · ca. 1656–57', image: 'art/437878.jpg',
          facts: [ { label: 'Movement', value: 'Dutch Golden Age' }, { label: 'Year', value: 'ca. 1656–57' } ],
          body: 'Window light and absolute stillness in a Delft room. Only around 35 Vermeers survive — scarcity is part of the spell.', source: 'Met Open Access (CC0)' },
        { id: 'e-hals', title: 'Young Man and Woman in an Inn', subtitle: 'Frans Hals · 1623', image: 'art/436616.jpg',
          facts: [ { label: 'Movement', value: 'Dutch Golden Age' }, { label: 'Year', value: '1623' } ],
          body: 'The laugh caught live, in strokes so loose the Impressionists claimed him as a grandfather.', source: 'Met Open Access (CC0)' },
      ],
    },
    {
      id: 'ex-renaissance-baroque',
      title: 'Renaissance north · Baroque south',
      blurb: 'Northern detail, Roman drama, Spanish soul.',
      kind: 'gallery',
      entries: [
        { id: 'e-bruegel', title: 'The Harvesters', subtitle: 'Pieter Bruegel the Elder · 1565', image: 'art/435809.jpg',
          facts: [ { label: 'Movement', value: 'Northern Renaissance' }, { label: 'Year', value: '1565' } ],
          body: 'Peasant labour and the turning year, seen from above — ordinary life given the scale once reserved for saints.', source: 'Met Open Access (CC0)' },
        { id: 'e-durer', title: 'Salvator Mundi', subtitle: 'Albrecht Dürer · ca. 1505', image: 'art/436243.jpg',
          facts: [ { label: 'Movement', value: 'Northern Renaissance' }, { label: 'Year', value: 'ca. 1505' } ],
          body: 'Dürer carried the Renaissance across the Alps — and through the printing press, across Europe.', source: 'Met Open Access (CC0)' },
        { id: 'e-caravaggio', title: 'The Denial of Saint Peter', subtitle: 'Caravaggio · 1610', image: 'art/437986.jpg',
          facts: [ { label: 'Movement', value: 'Baroque' }, { label: 'Year', value: '1610' } ],
          body: 'Sacred drama lit like a crime scene, painted in his final year. Half of Europe painted in his wake.', source: 'Met Open Access (CC0)' },
        { id: 'e-elgreco', title: 'Christ Healing the Blind', subtitle: 'El Greco · ca. 1570', image: 'art/436572.jpg',
          facts: [ { label: 'Movement', value: 'Mannerism / Spain' }, { label: 'Year', value: 'ca. 1570' } ],
          body: 'Flame-like figures lit from within. Nobody painted like him for three centuries — then the moderns claimed him.', source: 'Met Open Access (CC0)' },
        { id: 'e-velazquez', title: 'The Supper at Emmaus', subtitle: 'Velázquez · 1622–23', image: 'art/437871.jpg',
          facts: [ { label: 'Movement', value: 'Spanish Baroque' }, { label: 'Year', value: '1622–23' } ],
          body: '“The painter of painters” (Manet): loose strokes that dissolve up close and snap into focus at distance.', source: 'Met Open Access (CC0)' },
      ],
    },
    {
      id: 'ex-romantics',
      title: 'Revolution, Romantics & Realists',
      blurb: 'From Roman virtue to the sublime to just-paint-what-is.',
      kind: 'gallery',
      entries: [
        { id: 'e-david', title: 'The Death of Socrates', subtitle: 'Jacques-Louis David · 1787', image: 'art/436105.jpg',
          facts: [ { label: 'Movement', value: 'Neoclassicism' }, { label: 'Year', value: '1787' } ],
          body: 'Reason, calm, principle unto death — painted on the eve of the Revolution David would join.', source: 'Met Open Access (CC0)' },
        { id: 'e-goya', title: 'Josefa de Castilla Portugal', subtitle: 'Francisco de Goya · 1804', image: 'art/436543.jpg',
          facts: [ { label: 'Movement', value: 'Romanticism' }, { label: 'Year', value: '1804' } ],
          body: 'The court portraitist who would end in nightmares — Goya bridges courtly polish and modern unease.', source: 'Met Open Access (CC0)' },
        { id: 'e-friedrich', title: 'Two Men Contemplating the Moon', subtitle: 'Caspar David Friedrich · ca. 1825–30', image: 'art/438417.jpg',
          facts: [ { label: 'Movement', value: 'German Romanticism' }, { label: 'Year', value: 'ca. 1825–30' } ],
          body: 'His signature Rückenfigur — figures with their backs to us, so we stand inside the awe with them.', source: 'Met Open Access (CC0)' },
        { id: 'e-turner', title: 'Venice, from the Porch of Madonna della Salute', subtitle: 'J. M. W. Turner · ca. 1835', image: 'art/437853.jpg',
          facts: [ { label: 'Movement', value: 'Romanticism' }, { label: 'Year', value: 'ca. 1835' } ],
          body: 'Light and water dissolving stone — Impressionism decades ahead of schedule.', source: 'Met Open Access (CC0)' },
        { id: 'e-leutze', title: 'Washington Crossing the Delaware', subtitle: 'Emanuel Leutze · 1851', image: 'art/11417.jpg',
          facts: [ { label: 'Genre', value: 'History painting' }, { label: 'Year', value: '1851' } ],
          body: 'National myth staged for maximum drama — historically loose (that flag didn’t exist yet), emotionally exact.', source: 'Met Open Access (CC0)' },
        { id: 'e-courbet', title: 'The Source of the Loue', subtitle: 'Gustave Courbet · 1864', image: 'art/436023.jpg',
          facts: [ { label: 'Movement', value: 'Realism' }, { label: 'Year', value: '1864' } ],
          body: '“Show me an angel and I’ll paint one.” A plain river source, painted thick, at heroic scale.', source: 'Met Open Access (CC0)' },
      ],
    },
    {
      id: 'ex-impressionists',
      title: 'Impressionism & its sparks',
      blurb: 'Manet’s scandals, Japanese prints, and the circle that left the studio.',
      kind: 'gallery',
      entries: [
        { id: 'e-hokusai', title: 'The Great Wave off Kanagawa', subtitle: 'Katsushika Hokusai · ca. 1830–32', image: 'art/45434.jpg',
          facts: [ { label: 'Movement', value: 'Ukiyo-e (Japan)' }, { label: 'Medium', value: 'Woodblock print' } ],
          body: 'Cropped drama, flat colour, everyday subject — the print that helped teach Paris to see differently.', source: 'Met Open Access (CC0)' },
        { id: 'e-manet', title: 'Madame Manet at Bellevue', subtitle: 'Édouard Manet · 1880', image: 'art/438002.jpg',
          facts: [ { label: 'Movement', value: 'Impressionism (precursor)' }, { label: 'Year', value: '1880' } ],
          body: 'Never formally one of them, Manet opened the door — modern subjects, flat light, Salon scandals.', source: 'Met Open Access (CC0)' },
        { id: 'e-renoir', title: 'By the Seashore', subtitle: 'Auguste Renoir · 1883', image: 'art/437430.jpg',
          facts: [ { label: 'Movement', value: 'Impressionism' }, { label: 'Year', value: '1883' } ],
          body: 'Painted pleasure — soft air and dappled light on an afternoon by the sea.', source: 'Met Open Access (CC0)' },
        { id: 'e-degas', title: 'Dancer with a Fan', subtitle: 'Edgar Degas · ca. 1880', image: 'art/436135.jpg',
          facts: [ { label: 'Movement', value: 'Impressionism' }, { label: 'Year', value: 'ca. 1880' } ],
          body: 'Cropped and off-centre, as a camera or a Japanese print would frame it — a glimpse, not a pose.', source: 'Met Open Access (CC0)' },
        { id: 'e-seurat', title: 'The Mower', subtitle: 'Georges Seurat · 1881–82', image: 'art/459116.jpg',
          facts: [ { label: 'Movement', value: 'Toward pointillism' }, { label: 'Year', value: '1881–82' } ],
          body: 'Before the dots: the constructed calm that would become pointillism is already here.', source: 'Met Open Access (CC0)' },
        { id: 'e-homer', title: 'The Veteran in a New Field', subtitle: 'Winslow Homer · 1865', image: 'art/11145.jpg',
          facts: [ { label: 'Movement', value: 'American realism' }, { label: 'Year', value: '1865' } ],
          body: 'A Civil War elegy without a soldier in sight — the veteran mows a field that was recently a battlefield’s twin.', source: 'Met Open Access (CC0)' },
        { id: 'e-sargent', title: 'Madame X', subtitle: 'John Singer Sargent · 1883–84', image: 'art/12127.jpg',
          facts: [ { label: 'Movement', value: 'Society portrait' }, { label: 'Year', value: '1883–84' } ],
          body: 'The pallor and the strap scandalised the 1884 Salon; Sargent left Paris for London. Now it is the Met’s icon.', source: 'Met Open Access (CC0)' },
      ],
    },
    {
      id: 'ex-moderns',
      title: 'Toward modern art',
      blurb: 'Structure, feeling, symbol — the three roads out of Impressionism.',
      kind: 'gallery',
      entries: [
        { id: 'e-cezanne', title: 'The Card Players', subtitle: 'Paul Cézanne · 1890–92', image: 'art/435868.jpg',
          facts: [ { label: 'Movement', value: 'Post-Impressionism' }, { label: 'Legacy', value: 'Toward Cubism' } ],
          body: '“To make of Impressionism something solid and durable” — figures built from firm planes of colour.', source: 'Met Open Access (CC0)' },
        { id: 'e-vangogh', title: 'Wheat Field with Cypresses', subtitle: 'Vincent van Gogh · 1889', image: 'art/436535.jpg',
          facts: [ { label: 'Movement', value: 'Post-Impressionism' }, { label: 'Year', value: '1889' } ],
          body: 'Wheat, cypress and cloud writhing with the same thick stroke — paint itself carrying the feeling.', source: 'Met Open Access (CC0)' },
        { id: 'e-vangogh2', title: 'Madame Roulin and Her Baby', subtitle: 'Vincent van Gogh · 1888', image: 'art/459123.jpg',
          facts: [ { label: 'Movement', value: 'Post-Impressionism' }, { label: 'Year', value: '1888' } ],
          body: 'The Arles palette and urgent stroke turned to a portrait of his postman’s wife and daughter.', source: 'Met Open Access (CC0)' },
        { id: 'e-gauguin', title: 'Still Life with Teapot and Fruit', subtitle: 'Paul Gauguin · 1896', image: 'art/437999.jpg',
          facts: [ { label: 'Movement', value: 'Post-Impressionism' }, { label: 'Year', value: '1896 · Tahiti' } ],
          body: 'Colour freed from description — flat, symbolic, glowing, even on a tabletop.', source: 'Met Open Access (CC0)' },
        { id: 'e-klimt', title: 'Serena Pulitzer Lederer', subtitle: 'Gustav Klimt · 1899', image: 'art/436820.jpg',
          facts: [ { label: 'Movement', value: 'Vienna Secession' }, { label: 'Year', value: '1899' } ],
          body: 'The society portraitist on his way to the gold period — surface already beginning to shimmer.', source: 'Met Open Access (CC0)' },
        { id: 'e-hodler', title: 'The Dream of the Shepherd', subtitle: 'Ferdinand Hodler · 1896', image: 'art/634108.jpg',
          facts: [ { label: 'Movement', value: 'Symbolism' }, { label: 'Year', value: '1896' } ],
          body: 'Rhythmic, dreaming figures — Hodler’s “parallelism”; meaning carried by pattern, not realism.', source: 'Met Open Access (CC0)' },
        { id: 'e-rousseau', title: 'The Repast of the Lion', subtitle: 'Henri Rousseau · ca. 1907', image: 'art/438822.jpg',
          facts: [ { label: 'Movement', value: 'Naïve / Primitivism' }, { label: 'Year', value: 'ca. 1907' } ],
          body: 'Jungles from greenhouse visits by a self-taught toll collector. The avant-garde laughed — then Picasso threw him a banquet.', source: 'Met Open Access (CC0)' },
      ],
    },
    {
      id: 'movements',
      title: 'The timeline, in order',
      blurb: 'How Western painting loosened from precise representation toward pure feeling.',
      kind: 'list',
      entries: [
        { id: 'm-nren', title: 'Northern Renaissance', subtitle: '15th–16th c. · detail, oil, daily life',
          body: 'The perfected oil medium in Flanders and Germany: minute detail and everyday subjects rather than Italy’s idealised bodies. Names: Van Eyck, Dürer, Bruegel.', source: 'Art-historical consensus' },
        { id: 'm-baroque', title: 'Baroque', subtitle: '17th c. · drama and light',
          body: 'Caravaggio’s theatre of light spreads across Europe — and in Spain, Velázquez paints air itself. Names: Caravaggio, Velázquez, Rubens.', source: 'Art-historical consensus' },
        { id: 'm-dutch', title: 'Dutch Golden Age', subtitle: '17th c. · a republic of pictures',
          body: 'A Protestant merchant republic buys portraits, taverns and quiet rooms. Names: Rembrandt, Vermeer, Hals.', source: 'Art-historical consensus' },
        { id: 'm-neo-rom', title: 'Neoclassicism → Romanticism', subtitle: 'late 18th–19th c. · reason, then feeling',
          body: 'David’s Roman virtue gives way to Goya’s darkness, Friedrich’s sublime and Turner’s dissolving light.', source: 'Art-historical consensus' },
        { id: 'm-realism', title: 'Realism', subtitle: 'mid-19th c. · paint what is',
          body: 'Courbet frees subject matter; ordinary people and places at full scale. The hinge to modern art.', source: 'Art-historical consensus' },
        { id: 'm-impress', title: 'Impressionism', subtitle: '1860s–80s · the fleeting moment',
          body: 'Out of the studio, broken colour, modern life mid-motion. Names: Monet, Renoir, Degas — sparked by Manet and Japanese prints.', source: 'Art-historical consensus' },
        { id: 'm-post', title: 'Post-Impressionism & Symbolism', subtitle: '1880s–1900s · structure, feeling, symbol',
          body: 'Cézanne toward structure, Van Gogh toward emotion, Gauguin and Klimt toward the symbolic. The door to the twentieth century.', source: 'Art-historical consensus' },
      ],
    },
  ],
};
