import type { DomainContent } from '../knowledge-core/types';

// Art v0 — the "recognition layer" (image → artist, period, why it matters) plus the
// "understanding layer" (formal vocabulary), per spec 03 §3. Images are Met Open Access
// CC0 works, downloaded at authoring time and committed under public/art (offline gate).
export const ART: DomainContent = {
  id: 'art',
  title: 'Art',
  blurb: 'Recognise · read · understand',
  accent: '#b07d2c',
  newPerDay: 6,
  blocks: [
    {
      id: 'ways-of-looking',
      title: 'Ways of looking',
      primer: 'Before any chronology, learn to look. Without a formal vocabulary an art survey is just names attached to thumbnails.\n\nThese are the tools you use on every single work — the layer that turns recognising a painting into understanding it.',
      lessons: [
        { id: 'composition', title: 'Composition & line', body: 'Composition is how the artist arranges everything to lead your eye — balance, a focal point, the path your gaze travels. Notice where you look first, and what pulls you there.\n\nLine does two jobs: contour (the edges of things) and gesture (energy and movement). A diagonal feels active; a horizontal, calm. Much of a picture’s feeling is decided before you notice any subject.' },
        { id: 'colour-light', title: 'Colour, light, space', body: 'Colour carries temperature (warm advances, cool recedes) and relationships (complementaries intensify each other). Light models form: chiaroscuro is strong light-to-dark contrast for drama and volume — Caravaggio and Rembrandt are its masters.\n\nSpace is built by perspective — linear (converging lines) or atmospheric (distant things paler and bluer). And facture — visible brushwork — is itself expressive: smooth and hidden, or thick and gestural.' },
        { id: 'the-question', title: 'The one question', body: 'For every work, ask: what problem was this artist solving?\n\nThat single question is the understanding layer. Knowing Van Gogh painted a wheat field is a fact; seeing that he was trying to make paint itself carry emotion is the thing worth keeping. It stops the recognition cards from being a quiz.' },
      ],
    },
    {
      id: 'anchors',
      title: 'Reading a few masters',
      primer: 'The recognition layer trains your eye to place an unseen work — its hand, its period. Here are the anchors behind the review images.',
      lessons: [
        { id: 'dutch', title: 'Dutch Golden Age: Vermeer & Rembrandt', body: 'Vermeer turned ordinary interiors into contemplative worlds — a woman by a window, luminous natural light, absolute stillness.\n\nRembrandt used chiaroscuro not for theatrics but for psychology: faces emerging from shadow, carrying a lifetime of feeling. Between them, light does two different kinds of work — one quiet, one searching.' },
        { id: 'toward-modern', title: 'Toward the modern eye', body: 'Bruegel (Northern Renaissance) made peasant life and the turning seasons a grand subject, painted from a high, sweeping vantage.\n\nTurner (Romanticism) let light and atmosphere begin to dissolve solid form — anticipating Impressionism by decades. Degas (Impressionism) borrowed the cropped, off-centre framing of photography and Japanese prints. Van Gogh (Post-Impressionism) pushed thick, expressive colour toward pure feeling. Follow that thread and you can watch representation loosen into modern art.' },
      ],
    },
  ],
  cards: [
    // Understanding layer (formal vocabulary)
    { id: 'a-composition', type: 'why', prompt: 'In formal analysis, what does “composition” govern?',
      explanation: 'How the artist leads your eye — balance, focal point, and the path your gaze travels. Much of a picture’s feeling is set by arrangement before you register the subject.',
      source: 'Formal analysis', verified: true, tag: 'looking' },
    { id: 'a-chiaroscuro', type: 'cloze', prompt: 'Strong contrast of light and dark for drama and volume is called ___.',
      answer: 'chiaroscuro', accept: ['chiaroscuro'], explanation: 'From Italian “light-dark”. Masters: Caravaggio, Rembrandt.',
      source: 'Formal analysis', verified: true, tag: 'looking' },
    { id: 'a-question', type: 'why', prompt: 'The single question to ask of every artwork (the understanding layer)?',
      explanation: '“What problem was this artist solving?” It converts recognition into understanding.',
      source: 'Spec 03 §3', verified: true, tag: 'looking' },

    // Recognition layer (image → artist, period, why)
    { id: 'a-vangogh', type: 'instance', image: 'art/436535.jpg', prompt: 'Who painted this?',
      answer: 'Van Gogh', accept: ['van gogh', 'vincent van gogh', 'gogh'],
      explanation: 'Van Gogh, “Wheat Field with Cypresses” (1889). Post-Impressionism — swirling impasto and heightened colour make paint itself carry feeling.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Post-Impressionism' },
    { id: 'a-vermeer', type: 'instance', image: 'art/437878.jpg', prompt: 'Who painted this?',
      answer: 'Vermeer', accept: ['vermeer', 'johannes vermeer'],
      explanation: 'Vermeer, “A Maid Asleep” (ca. 1656–57). Dutch Golden Age — luminous domestic light and profound stillness.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Dutch Golden Age' },
    { id: 'a-rembrandt', type: 'instance', image: 'art/437398.jpg', prompt: 'Who painted this?',
      answer: 'Rembrandt', accept: ['rembrandt', 'rembrandt van rijn'],
      explanation: 'Rembrandt, “Flora” (ca. 1654). Dutch Golden Age — chiaroscuro used for psychological depth, not just drama.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Dutch Golden Age' },
    { id: 'a-bruegel', type: 'instance', image: 'art/435809.jpg', prompt: 'Who painted this?',
      answer: 'Bruegel', accept: ['bruegel', 'brueghel', 'pieter bruegel', 'pieter bruegel the elder'],
      explanation: 'Bruegel the Elder, “The Harvesters” (1565). Northern Renaissance — everyday peasant life and season raised to a grand subject.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Northern Renaissance' },
    { id: 'a-turner', type: 'instance', image: 'art/383001.jpg', prompt: 'Who made this?',
      answer: 'Turner', accept: ['turner', 'jmw turner', 'j.m.w. turner', 'william turner'],
      explanation: 'J.M.W. Turner, from the “Liber Studiorum” (1811). Romanticism — light and atmosphere begin to dissolve solid form, decades before Impressionism.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Romanticism' },
    { id: 'a-degas', type: 'instance', image: 'art/436135.jpg', prompt: 'Who made this?',
      answer: 'Degas', accept: ['degas', 'edgar degas'],
      explanation: 'Degas, “Dancer with a Fan” (ca. 1880). Impressionism — cropped, off-centre framing borrowed from photography and Japanese prints.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Impressionism' },
    { id: 'a-hokusai', type: 'instance', image: 'art/45434.jpg', prompt: 'Who made this?',
      answer: 'Hokusai', accept: ['hokusai', 'katsushika hokusai'],
      explanation: 'Hokusai, “Under the Wave off Kanagawa” — the Great Wave (ca. 1830–32). Japanese ukiyo-e woodblock print; prints like this shaped Impressionism.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Ukiyo-e' },
    { id: 'a-cezanne', type: 'instance', image: 'art/435868.jpg', prompt: 'Who painted this?',
      answer: 'Cézanne', accept: ['cezanne', 'cézanne', 'paul cezanne', 'paul cézanne'],
      explanation: 'Cézanne, “The Card Players” (1890–92). Post-Impressionism — building solid structure from planes of colour, a bridge to Cubism.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Post-Impressionism' },
    { id: 'a-david', type: 'instance', image: 'art/436105.jpg', prompt: 'Who painted this?',
      answer: 'David', accept: ['david', 'jacques louis david', 'jacques-louis david'],
      explanation: 'Jacques-Louis David, “The Death of Socrates” (1787). Neoclassicism — cool clarity, moral seriousness, sculptural figures.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Neoclassicism' },
    { id: 'a-leutze', type: 'instance', image: 'art/11417.jpg', prompt: 'Who painted this?',
      answer: 'Leutze', accept: ['leutze', 'emanuel leutze'],
      explanation: 'Emanuel Leutze, “Washington Crossing the Delaware” (1851). Grand history painting — heroic narrative on a monumental scale.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'History painting' },
    { id: 'a-hodler', type: 'instance', image: 'art/634108.jpg', prompt: 'Who painted this?',
      answer: 'Hodler', accept: ['hodler', 'ferdinand hodler'],
      explanation: 'Ferdinand Hodler, “The Dream of the Shepherd” (1896). Symbolism — rhythmic, dreamlike figures carrying inner meaning over realism.',
      source: 'Met Open Access (CC0)', verified: true, tag: 'Symbolism' },
  ],

  explore: [
    {
      id: 'gallery',
      title: 'The gallery',
      blurb: 'Open a work and read what its maker was actually trying to do. All images are Met Open Access (CC0).',
      kind: 'gallery',
      entries: [
        { id: 'e-bruegel', title: 'The Harvesters', subtitle: 'Pieter Bruegel the Elder · 1565', image: 'art/435809.jpg',
          facts: [ { label: 'Movement', value: 'Northern Renaissance' }, { label: 'Year', value: '1565' }, { label: 'Where', value: 'The Met, New York' } ],
          body: 'One of a series on the seasons. Bruegel takes ordinary peasant labour — reaping wheat, dozing after lunch — and gives it the scale and dignity usually reserved for religion or myth.\n\nThe high vantage point lets the eye travel from the golden foreground deep into a hazy valley: everyday life seen whole, as a turning of the year.',
          source: 'Met Open Access (CC0)' },
        { id: 'e-rembrandt', title: 'Flora', subtitle: 'Rembrandt van Rijn · ca. 1654', image: 'art/437398.jpg',
          facts: [ { label: 'Movement', value: 'Dutch Golden Age' }, { label: 'Year', value: 'ca. 1654' }, { label: 'Technique', value: 'Chiaroscuro' } ],
          body: 'Rembrandt uses chiaroscuro — deep shadow pierced by warm light — not for theatrics but for inwardness. The figure emerges from darkness as if from thought.\n\nThe problem he was solving all his life: how to make paint carry a human interior, not just a likeness.',
          source: 'Met Open Access (CC0)' },
        { id: 'e-vermeer', title: 'A Maid Asleep', subtitle: 'Johannes Vermeer · ca. 1656–57', image: 'art/437878.jpg',
          facts: [ { label: 'Movement', value: 'Dutch Golden Age' }, { label: 'Year', value: 'ca. 1656–57' }, { label: 'Subject', value: 'Domestic interior' } ],
          body: 'Vermeer makes an ordinary room contemplative. Natural light falls with such calm precision that stillness itself becomes the subject.\n\nHis question: how much quiet can a picture hold and still feel alive? The answer is what makes a Vermeer unmistakable.',
          source: 'Met Open Access (CC0)' },
        { id: 'e-turner', title: 'From the Liber Studiorum', subtitle: 'J. M. W. Turner · 1811', image: 'art/383001.jpg',
          facts: [ { label: 'Movement', value: 'Romanticism' }, { label: 'Year', value: '1811' }, { label: 'Legacy', value: 'Anticipates Impressionism' } ],
          body: 'Turner lets light and atmosphere begin to dissolve solid form — sea, sky and land blurring into a single luminous field.\n\nDecades before the Impressionists, he was already asking whether a painting could be about light itself rather than the things light falls on.',
          source: 'Met Open Access (CC0)' },
        { id: 'e-degas', title: 'Dancer with a Fan', subtitle: 'Edgar Degas · ca. 1880', image: 'art/436135.jpg',
          facts: [ { label: 'Movement', value: 'Impressionism' }, { label: 'Year', value: 'ca. 1880' }, { label: 'Influences', value: 'Photography · Japanese prints' } ],
          body: 'Degas crops the figure off-centre and cuts it at the edge, as a camera or a Japanese woodblock print would — a glimpse, not a pose.\n\nHe was solving how to paint modern life as it is actually seen: in passing, at an angle, mid-movement.',
          source: 'Met Open Access (CC0)' },
        { id: 'e-vangogh', title: 'Wheat Field with Cypresses', subtitle: 'Vincent van Gogh · 1889', image: 'art/436535.jpg',
          facts: [ { label: 'Movement', value: 'Post-Impressionism' }, { label: 'Year', value: '1889' }, { label: 'Technique', value: 'Impasto' } ],
          body: 'Every element — wheat, cypress, cloud — writhes with the same thick, visible brushstroke. Van Gogh is not describing a field; he is making the paint itself carry emotion.\n\nThat shift, from depicting the world to expressing a response to it, is the doorway to modern art.',
          source: 'Met Open Access (CC0)' },
        { id: 'e-david', title: 'The Death of Socrates', subtitle: 'Jacques-Louis David · 1787', image: 'art/436105.jpg',
          facts: [ { label: 'Movement', value: 'Neoclassicism' }, { label: 'Year', value: '1787' }, { label: 'Mood', value: 'Stoic, moral' } ],
          body: 'Socrates reaches for the hemlock while still teaching, calm amid grief. David strips away decoration for cool clarity and sculptural bodies — reason and virtue over Rococo prettiness.\n\nPainted on the eve of the French Revolution, it made Neoclassicism a moral and political language.',
          source: 'Met Open Access (CC0)' },
        { id: 'e-hokusai', title: 'The Great Wave off Kanagawa', subtitle: 'Katsushika Hokusai · ca. 1830–32', image: 'art/45434.jpg',
          facts: [ { label: 'Movement', value: 'Ukiyo-e (Japan)' }, { label: 'Medium', value: 'Woodblock print' }, { label: 'Influence', value: 'Shaped Impressionism' } ],
          body: 'A towering wave curls over tiny boats, with Mount Fuji small and steady behind. Flattened space, bold outline and cropped drama — the language of the Japanese woodblock print.\n\nWhen prints like this reached Paris, they upended European ideas of composition and helped launch Impressionism (“Japonisme”).',
          source: 'Met Open Access (CC0)' },
        { id: 'e-cezanne', title: 'The Card Players', subtitle: 'Paul Cézanne · 1890–92', image: 'art/435868.jpg',
          facts: [ { label: 'Movement', value: 'Post-Impressionism' }, { label: 'Year', value: '1890–92' }, { label: 'Legacy', value: 'Toward Cubism' } ],
          body: 'Two men bent over cards, built from firm planes of colour rather than fleeting light. Cézanne wanted the solidity the Impressionists had dissolved — “to make of Impressionism something solid and durable.”\n\nThat search for underlying structure led directly to Picasso and Cubism.',
          source: 'Met Open Access (CC0)' },
        { id: 'e-hodler', title: 'The Dream of the Shepherd', subtitle: 'Ferdinand Hodler · 1896', image: 'art/634108.jpg',
          facts: [ { label: 'Movement', value: 'Symbolism' }, { label: 'Year', value: '1896' }, { label: 'Idea', value: 'Inner meaning over realism' } ],
          body: 'A dreaming figure and floating forms in rhythmic arrangement — Hodler’s “parallelism.” Symbolists turned from the everyday toward mood, myth and the inner life.\n\nMeaning is carried by pattern and suggestion, not by describing a real scene.',
          source: 'Met Open Access (CC0)' },
        { id: 'e-leutze', title: 'Washington Crossing the Delaware', subtitle: 'Emanuel Leutze · 1851', image: 'art/11417.jpg',
          facts: [ { label: 'Genre', value: 'History painting' }, { label: 'Year', value: '1851' }, { label: 'Scale', value: 'Monumental' } ],
          body: 'A founding national myth staged for maximum drama: dawn light, ice-choked river, Washington resolute at the prow. Historically loose (that flag didn’t yet exist), but that was never the point.\n\nGrand history painting aimed to stir shared feeling, not to document.',
          source: 'Met Open Access (CC0)' },
      ],
    },
    {
      id: 'movements',
      title: 'Movements, in order',
      blurb: 'A short timeline — how Western painting loosened from precise representation toward pure feeling.',
      kind: 'list',
      entries: [
        { id: 'm-nren', title: 'Northern Renaissance', subtitle: '15th–16th century · Low Countries & Germany',
          facts: [ { label: 'Marks', value: 'Minute detail, oil glazes' }, { label: 'Names', value: 'Van Eyck, Bruegel, Dürer' } ],
          body: 'Northern painters used the newly perfected oil medium for astonishing detail and everyday subjects — landscapes, interiors, peasant life — rather than the idealised bodies of the Italian Renaissance.',
          source: 'Art-historical consensus' },
        { id: 'm-dutch', title: 'Dutch Golden Age', subtitle: '17th century · Netherlands',
          facts: [ { label: 'Marks', value: 'Light, realism, domestic scale' }, { label: 'Names', value: 'Rembrandt, Vermeer, Hals' } ],
          body: 'A wealthy merchant republic wanted portraits, still lifes and interiors, not altarpieces. The result: an unmatched study of light and ordinary life, from Rembrandt’s shadow to Vermeer’s window.',
          source: 'Art-historical consensus' },
        { id: 'm-romantic', title: 'Romanticism', subtitle: 'late 18th–19th century · Europe',
          facts: [ { label: 'Marks', value: 'Emotion, nature, the sublime' }, { label: 'Names', value: 'Turner, Friedrich, Delacroix' } ],
          body: 'A reaction against cool Neoclassical order: feeling over reason, wild nature over the city, awe and terror (the “sublime”). Turner’s dissolving light pointed straight at what came next.',
          source: 'Art-historical consensus' },
        { id: 'm-impress', title: 'Impressionism', subtitle: '1860s–1880s · France',
          facts: [ { label: 'Marks', value: 'Broken colour, painted outdoors, the fleeting moment' }, { label: 'Names', value: 'Monet, Degas, Renoir' } ],
          body: 'Painters left the studio to catch changing light with quick, broken strokes of unmixed colour. They painted the impression of a moment — a departure that scandalised the official Salon.',
          source: 'Art-historical consensus' },
        { id: 'm-post', title: 'Post-Impressionism', subtitle: '1880s–1900s · France',
          facts: [ { label: 'Marks', value: 'Structure & emotion beyond the fleeting' }, { label: 'Names', value: 'Van Gogh, Cézanne, Gauguin' } ],
          body: 'Building on Impressionism but reaching further: Cézanne toward underlying structure, Van Gogh toward raw emotion, Gauguin toward symbolic colour. Together they opened the door to twentieth-century modern art.',
          source: 'Art-historical consensus' },
      ],
    },
  ],
};
